- .github/workflows/ci.yml
Update package name from `nginx-agent-snapshot.tar.gz` to `nginx-agent.tar.gz`
> Update package name

- .github/workflows/release-branch.yml
- Makefile
* Upload individual packages on release instead of tarball containing all
> Upload individual packages on release

- .github/workflows/release-branch.yml
Update github release upload to upload the freebsd packages in a zip file.
> Update github release upload to upload the freebsd packages in a zip file.

- .github/release-drafter.yml
- .github/workflows/ci.yml
- Updated CI workflow to run on PRs, the main branch and release branches.
- Updated autolabeler config.
> Updated CI workflow to run on PRs

- .github/workflows/ci.yml
Update release branch regex in CI workflow trigger
> Update release branch regex in CI workflow trigger

- .github/workflows/release-branch.yml
Fix freebsd package path in release branch workflow
> Fix freebsd package path in release branch workflow

- .github/workflows/release-branch.yml
Update FreeBSD package path in release branch workflow
> Update FreeBSD package path in release branch workflow

- Makefile
- test/integration/api/api_test.go
- test/integration/install/install_uninstall_test.go
- test/integration/utils/test_container_utils.go
* Add assertion that there are no logs at error level in integration tests
> Add assertion for no error level logs in tests

- Makefile
Changing the install tools to install and not run the githook
> change from run to install for git hooks

- .github/workflows/ci.yml
Wait until integration tests pass before kicking off release workflow
> Wait until integration tests pass before kicking off release workflow

- src/plugins/nginx.go
- src/plugins/nginx_test.go
- test/performance/vendor/github.com/nginx/agent/v2/src/plugins/nginx.go
> Pid drain check

- sdk/client/commander_test.go
Validation of tests in actions
> added waitgroup done in tests

- hugo/content/technical-specifications.md
Adding a set of operating systems to NGINX Agent docs of which OSs are currently supported. 
> Add Supported distributions

- scripts/docker/nginx-oss/rpm/Dockerfile
* Replace usage of fedora epel repo with oracle repo
> Fix replace usage of flaky epel repo

- scripts/docker/nginx-plus/almalinux/Dockerfile
- scripts/docker/nginx-plus/rockylinux/Dockerfile
Added the ability to run plus images with Alma and Rocky Linux
> added plus images for rocky and alma

- scripts/packages/postremove.sh
* Postremove cleanup changes are causing issues with upgrade scenarios.
* Revert changes from:  https://github.com/nginx/agent/commit/53063768041ff9655c1e3db8227d50295e31c157
> Revert postremove cleanup changes

- hugo/content/technical-specifications.md
Updating NGINX Agent docs to reflect the new OS support in latest release.
> Update OS Support Docs

- .github/workflows/ci.yml
- .github/workflows/release-branch.yml
- Makefile.packaging
- scripts/packages/packager/signed-entrypoint.sh
Upload individual packages to Azure in pipeline 
> Fix Packaging 

- .github/workflows/ci.yml
- test/integration/utils/test_container_utils.go
* Integration tests will now be uploaded as build artefacts to assist in debugging failures in CI
> Add capture integration test docker logs

- .github/dependabot.yml
- .github/workflows/ci.yml
Update the pipelines so dependabot can run successfully
> dependabot pipeline conditions

- Makefile
- hugo/content/installation-oss.md
- hugo/content/installation-plus.md
- scripts/docker/official/nginx-oss-with-nginx-agent/alpine/Dockerfile
- scripts/docker/official/nginx-oss-with-nginx-agent/alpine/Dockerfile.mainline
- scripts/docker/official/nginx-oss-with-nginx-agent/alpine/docker-compose.yml
- scripts/docker/official/nginx-oss-with-nginx-agent/alpine/entrypoint.sh
- scripts/docker/official/nginx-plus-with-nginx-agent/alpine/Dockerfile
- scripts/docker/official/nginx-plus-with-nginx-agent/alpine/docker-compose.yml
- scripts/docker/official/nginx-plus-with-nginx-agent/alpine/entrypoint.sh
Add official Dockerfiles for NGINX OSS & Plus images that have the NGINX Agent installed on them as well.
> Add Dockerfiles & docker-compose files for official OSS & Plus images

- Makefile.packaging
`nginx-agent-2.26.1.amazon2.ngx.x86_64.rpm` -> `nginx-agent-2.26.1.amzn2.ngx.aarch64.rpm`
`nginx-agent-2.26.1.amazon-2023.ngx.x86_64.rpm` -> `nginx-agent-2.26.1.amzn2023.ngx.x86_64.rpm`
> fix amazon packaging

- main.go
- sdk/client/client.go
- sdk/client/commander.go
- src/core/config/config.go
- src/core/config/defaults.go
- src/core/config/types.go
- src/plugins/commander.go
- src/plugins/config_reader.go
- src/plugins/metrics_sender.go
- src/plugins/metrics_sender_test.go
- test/integration/vendor/github.com/nginx/agent/sdk/v2/client/client.go
- test/integration/vendor/github.com/nginx/agent/sdk/v2/client/commander.go
- test/performance/vendor/github.com/nginx/agent/sdk/v2/client/client.go
- test/performance/vendor/github.com/nginx/agent/sdk/v2/client/commander.go
- test/performance/vendor/github.com/nginx/agent/v2/src/core/config/config.go
- test/performance/vendor/github.com/nginx/agent/v2/src/core/config/defaults.go
- test/performance/vendor/github.com/nginx/agent/v2/src/core/config/types.go
- test/performance/vendor/github.com/nginx/agent/v2/src/plugins/commander.go
- test/performance/vendor/github.com/nginx/agent/v2/src/plugins/config_reader.go
- test/performance/vendor/github.com/nginx/agent/v2/src/plugins/metrics_sender.go
- vendor/github.com/nginx/agent/sdk/v2/client/client.go
- vendor/github.com/nginx/agent/sdk/v2/client/commander.go
> Fix backoff settings

- .github/workflows/ci.yml
Dependabot changed the branches to *dependabot-* so updating accordingly
> change branch pattern

- .github/workflows/ci.yml
- go.work.sum
Get the pipeline versions to match go.mod
> Change the versions to match the go.mod

- src/extensions/advanced_metrics.go
- test/performance/advanced-metrics/fake_agent/agent.go
- test/performance/vendor/github.com/nginx/agent/v2/src/extensions/advanced_metrics.go
Enhanced advanced metrics to accept new ADM resource name dimensions.
- [✔️] I have read the [`CONTRIBUTING`](https://github.com/nginx/agent/blob/main/docs/CONTRIBUTING.md) document
- [✔️] I have run ```make install-tools``` and have attached any dependency changes to this pull request
- [✔️] If applicable, I have added tests that prove my fix is effective or that my feature works
- [✔️] If applicable, I have checked that any relevant tests pass after adding my changes
> feat: Add ADM resource name dimensions

- src/core/environment.go
- test/integration/vendor/github.com/nginx/agent/v2/src/core/environment.go
- test/performance/vendor/github.com/nginx/agent/v2/src/core/environment.go
Filter out commands that include upgrade in the command (how NGINX updates)
> fix for dash during upgrade

- scripts/selinux/README.md
- vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
> Update selinux readme

- main.go
- vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
Only create metrics sender if a metric reporter is already created
> Only create metrics sender if a metric reporter is already created

- main.go
- src/plugins/common.go
- src/plugins/common_test.go
- src/plugins/events.go
- src/plugins/events_test.go
- src/plugins/features.go
- src/plugins/features_test.go
- test/performance/plugins_test.go
- test/performance/vendor/github.com/nginx/agent/v2/src/plugins/common.go
- test/performance/vendor/github.com/nginx/agent/v2/src/plugins/events.go
- test/performance/vendor/github.com/nginx/agent/v2/src/plugins/features.go
Fix config apply failure on main
> Fix config apply

- test/symbols-local.json
> Remove unused test file

- .github/workflows/ci.yml
- Makefile
- scripts/docker/nginx-oss/apk/Dockerfile
Pre build packages for integration tests so every test doesn't build all local packages 
* This means that make `local-deb-package` for example will need to be run before `make integration-test ` 
> pre build packages for integration tests

- hugo/content/getting-started.md
* Add link to getting-started page on how to configure logrotation
> Add link in docs on how to configure logrotation

- site/content/configuration/_index.md
- site/content/configuration/configuration-overview.md
- site/content/configuration/encrypt-communication.md
- site/content/contribute/_index.md
- site/content/contribute/community.md
- site/content/contribute/dev-environment-setup.md
- site/content/installation-upgrade/_index.md
- site/content/installation-upgrade/container-environments/_index.md
- site/content/installation-upgrade/container-environments/docker-images.md
- site/content/installation-upgrade/container-environments/docker-support.md
- site/content/installation-upgrade/getting-started.md
- site/content/installation-upgrade/installation-github.md
- site/content/installation-upgrade/installation-oss.md
- site/content/installation-upgrade/installation-plus.md
- site/content/installation-upgrade/uninstall.md
- site/content/installation-upgrade/upgrade.md
- site/content/overview.md
- site/content/technical-specifications.md
Refactors the Information Architecture of the docs.nginx.com documentation.
- Docs moved to different folders by subject
- Adds two docs coming from the NMS documentation
- Metadata improvements
> feat: Agent Docs IA refactor

- .golangci.yml
- internal/bus/fake_message_pipe.go
- internal/bus/message_pipe.go
- internal/datasource/config/config_writer.go
- internal/service/config/nginx.go
- internal/service/instance.go
- internal/service/instance/instance.go
- internal/service/instance/instancefakes/fake_dataplane_instance_service.go
- internal/service/instance/nginx.go
- internal/service/instance/nginx_gateway_fabric.go
- internal/service/instance/nginx_test.go
- internal/service/instance_test.go
- Enable cognitive-complexity & cyclomatic rules in linter
- Reduce code complexity in code base
> Reduce code complexity

- internal/client/clientfakes/fake_config_client_interface.go
- internal/client/http_config_client.go
- internal/config/config.go
- internal/config/config_test.go
- internal/config/testdata/nginx-agent.conf
- internal/config/types.go
- internal/datasource/config/config_writer.go
- internal/datasource/config/config_writer_test.go
- nginx-agent.conf
Add allowed directories list to agent config
Write now checks if filepath is in allowed directories list 
> Add allowed dir list

- site/content/changelog.md
Adds the imported changelog from GitHub into the docs.nginx.com site docs.
Remove the existing redirect from that section of the docs to GitHub.
> feat: import changelog from github

- .github/workflows/ci.yml
Parity of the makefile and github action for linting
> run the lint action from the make file

- .github/workflows/ci.yml
- .testcoverage.yaml
- Makefile
- Makefile.tools
- README.md
- internal/client/http_config_client_test.go
- internal/datasource/host/exec/exec_test.go
- internal/datasource/host/process_test.go
When adding new code, we want to ensure that most of our code paths have been unit tested before merging anything to main/v3. Ideally our code would be 80% covered.
* Add a code coverage check to our PRs, which requires 80% minimum coverage to pass
* (Stretch): add a code coverage status badge to the project on GitHub.
* GitHub of chosen Action: https://github.com/vladopajic/go-test-coverage
* Method of badge generation: https://github.com/vladopajic/go-test-coverage/blob/main/docs/badge.md#coverage-badge-hosted-on-same-github-repository
> test: add go-test-coverage

- .github/release.yml
Adds the "Highlights" section and label to the changelog template
> Update release.yml to add a highlights section

- internal/app.go
- internal/config/defaults.go
- internal/metrics/export/otel.go
- internal/metrics/export/otel_test.go
- internal/plugin/data_plane_server.go
- internal/plugin/data_plane_server_test.go
- internal/plugin/metrics_plugin.go
- internal/plugin/metrics_plugin_test.go
- internal/plugin/plugin_manager.go
- internal/plugin/process_monitor_plugin.go
Fixed the graceful shutdown of the app.go and the DataPlane server API. Tidied much test code.
> fixed the graceful shutdown of the app and the DataPlane API server

- internal/client/http_config_client_test.go
- internal/datasource/config/cache_test.go
- internal/datasource/config/config_writer_test.go
- internal/datasource/nginx/nginx_process_test.go
- internal/logger/logger_test.go
- internal/metrics/export/otel_test.go
- internal/plugin/config_plugin_test.go
- internal/plugin/data_plane_server_test.go
- internal/plugin/grpc_client_plugin_test.go
- internal/plugin/metrics_plugin_test.go
- internal/plugin/plugin_manager_test.go
- internal/service/config/nginx_config_service_test.go
- internal/service/config_service_test.go
- internal/service/instance/nginx_instance_service_test.go
Update unit test names to make them easier to read
> Update unit test names

- cmd/agent/main.go
- internal/app.go
- internal/bus/fake_message_pipe.go
- internal/bus/message_pipe.go
- internal/bus/message_pipe_test.go
- internal/client/http_config_client_test.go
- internal/config/config.go
- internal/datasource/config/config_writer_test.go
- internal/datasource/host/process.go
- internal/plugin/config_plugin.go
- internal/plugin/config_plugin_test.go
- internal/plugin/data_plane_server.go
- internal/plugin/data_plane_server_test.go
- internal/plugin/grpc_client_plugin.go
- internal/plugin/grpc_client_plugin_test.go
- internal/plugin/instance_plugin.go
- internal/plugin/instance_plugin_test.go
- internal/plugin/metrics_plugin.go
- internal/plugin/metrics_plugin_test.go
- internal/plugin/process_monitor_plugin.go
- internal/plugin/process_monitor_plugin_test.go
- internal/service/config/nginx_config_service.go
- internal/service/config_service_test.go
- test/integration/data_plane_api_test.go
- test/integration/grpc_connection_test.go
- Refactor how context is used
- Refactor how we gracefully shutdown the agent
> Refactor how context is used

- test/performance/user_workflow_test.go
Fix user workflow performance tests
> Fix user workflow performance tests

- internal/service/config/nginx_config_service_benchmark_test.go
- test/config/nginx/nginx-with-10k-lines.conf
- test/config/nginx/nginx-with-1k-lines.conf
- test/config/nginx/nginx-with-2k-lines.conf
- test/config/nginx/nginx-with-3k-lines.conf
Add more configs for ParseConfig performance test.
> Add more configs for ParseConfig performance test

- internal/config/config.go
- internal/config/config_test.go
- internal/config/flags.go
- internal/config/types.go
- internal/grpc/credentials.go
- internal/grpc/credentials_test.go
- internal/grpc/grpc.go
- internal/plugin/grpc_client_plugin.go
Updated interceptor headers. Added uuid to agent config
> Add uuid and rename token to authorization header for gRPC connections

- cmd/agent/main.go
- test/mock/grpc/cmd/main.go
- test/mock/grpc/mock_management_command_service.go
Identified some log statements that had missing context. Adding them in
> added missing context to log statements

- internal/plugin/plugin_manager.go
- internal/plugin/resource_plugin.go
- internal/plugin/resource_plugin_test.go
- internal/service/config/nginx_config_service.go
- internal/service/instance/agent_instance_service.go
- internal/service/instance/agent_instance_service_test.go
- internal/service/instance_service.go
- internal/service/instance_service_test.go
- test/integration/grpc_management_plane_api_test.go
- test/types/config.go
* agent_instance_service
Added NGINX Agent instance service to report the Agent as an instance 
* resource_plugin
Pass the Agent Config into the resource plugin to utilize the config attributes
* instance_service
Pass the Agent Config into the instance service so that the new Agent Instance service can get the config attributes
* test config
Updated test config with UUID, Version and Path values
> Added Agent instance to resource payload

- internal/bus/topics.go
- internal/plugin/grpc_client_plugin.go
- internal/plugin/grpc_client_plugin_test.go
- test/mock/grpc/mock_management_command_service.go
- Handle context done in mock management plane subscribe function
- Clean up subscriptions in grpc client plugin
> Handle context done in mock management plane subscribe function

- .github/workflows/ci.yml
- go.mod
Change go.mod version from v1.22.2 to v1.22
> Change go.mod version from v1.22.2 to v1.22

- go.mod
- internal/app.go
- internal/datasource/host/hostfakes/fake_info_interface.go
- internal/datasource/host/info.go
- internal/grpc/grpc.go
- internal/grpc/grpc_test.go
- internal/plugin/grpc_client_plugin.go
- Send resource id as id in rpc dial options
- Add gotoolchain version to go.mod
> Send resource id as id in rpc dial options

- .github/workflows/v3-release.yml
Add a agent V3 release workflow
> V3 release workflow

- .github/workflows/ci.yml
- .github/workflows/label-pr.yml
- .github/workflows/release-branch.yml
Restrict workflows top level permissions
> Restrict workflows top level permissions

- scripts/docker/nginx-oss/rpm/Dockerfile
Change gid in oracle linux 9 dockerfile
> Fix oracle linux integration test

- site/content/_index.md
- site/content/configuration/configuration-overview.md
- site/content/configuration/configure-nginx-agent-group.md
- site/content/configuration/encrypt-communication.md
- site/content/contribute/community.md
- site/content/contribute/dev-environment-setup.md
- site/content/installation-upgrade/_index.md
- site/content/installation-upgrade/container-environments/docker-images.md
- site/content/installation-upgrade/container-environments/docker-support.md
- site/content/installation-upgrade/getting-started.md
- site/content/installation-upgrade/installation-github.md
- site/content/installation-upgrade/installation-oss.md
- site/content/installation-upgrade/installation-plus.md
- site/content/installation-upgrade/uninstall.md
- site/content/installation-upgrade/upgrade.md
- site/content/technical-specifications.md
Change Title Case to Sentence case in docs titles in v3 branch
- Update tech specs description
> fix: fix title case in v3 branch

- test/config/nginx/nginx-with-10k-lines.conf
- test/config/nginx/nginx-with-1k-lines.conf
- test/config/nginx/nginx-with-2k-lines.conf
- test/config/nginx/nginx-with-3k-lines.conf
Remove stub status location from performance test config files
> Remove stub status location from performance test config files

- internal/watcher/instance_watcher_service.go
- internal/watcher/instance_watcher_service_test.go
- internal/watcher/watcher_plugin.go
- internal/watcher/watcher_plugin_test.go
> Report instance updates

- site/content/changelog.md
> Update changelog for release 2.34

- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- .github/workflows/dependency-review.yml
- .github/workflows/label-pr.yml
- .github/workflows/release-branch.yml
- .github/workflows/scorecards.yml
- Makefile
- Makefile.packaging
- scripts/docker/nginx-oss/deb/Dockerfile
- scripts/docker/nginx-plus/debian/Dockerfile
- scripts/docker/nginx-plus/ubuntu/Dockerfile
- scripts/packages/postinstall.sh
- site/content/installation-upgrade/container-environments/docker-images.md
- site/content/technical-specifications.md
- test/docker/Dockerfile
- test/integration/Dockerfile
- test/integration/install/install_uninstall_test.go
* Add support for Ubuntu Noble 24.04
* Update CI/tests to use 24.04
* Update docs to include 24.04
* Fix OS detection in Makefile
> Add Ubuntu Noble 24.04 LTS support

- .github/workflows/release-branch.yml
Pass URL into make release in pipeline
> update release workflow to take env variable

- internal/watcher/health/health_watcher_service.go
- internal/watcher/health/health_watcher_service_test.go
- test/protos/instances.go
Increase health watcher test coverage to stop pipeline failing
> Increase health watcher test coverage

- Makefile
Update performance test make target
> Update performance test make target

- Makefile
- internal/watcher/instance/nginx_config_parser.go
- internal/watcher/instance/nginx_config_parser_benchmark_test.go
- internal/watcher/instance/nginx_config_parser_test.go
- pkg/files/file_helpers.go
- pkg/files/file_helpers_test.go
- test/helpers/config_utils.go
- test/mock/grpc/mock_management_file_service.go
Change how the file hash is generated 
> Change file hash

- site/content/configuration/configuration-overview.md
Update the tags and instance group examples on the configuration overview page. This makes the examples more optimal and applicable to real-world scenarios. 
> Update configuration examples

- Makefile
The version check was incorrect. Fixing
> Fix for version

- .golangci.yml
- internal/backoff/backoff_test.go
- internal/bus/message_pipe.go
- internal/bus/message_pipe_test.go
- internal/collector/otel_collector_plugin.go
- internal/command/command_service.go
- internal/config/config_test.go
- internal/config/types.go
- internal/datasource/host/info.go
- internal/datasource/host/info_test.go
- internal/file/file_plugin_test.go
- internal/grpc/grpc_test.go
- internal/logger/logger_test.go
- internal/model/config.go
- internal/model/os.go
- internal/resource/nginx_instance_operator_test.go
- internal/resource/nginx_log_tailer_operator_test.go
- internal/resource/resource_service.go
- internal/resource/resource_service_test.go
- internal/watcher/health/health_watcher_service_test.go
- internal/watcher/health/nginx_health_watcher_operator_test.go
- internal/watcher/instance/instance_watcher_service.go
- internal/watcher/instance/instance_watcher_service_test.go
- internal/watcher/instance/nginx_config_parser_test.go
- internal/watcher/instance/nginx_process_parser.go
- internal/watcher/instance/nginx_process_parser_test.go
- pkg/files/file_helpers_test.go
- test/load/nginx_agent_process_collector.go
- test/mock/grpc/mock_management_command_service.go
- test/mock/grpc/mock_management_file_service.go
Added fieldalignment to optimize structs for padding efficiency. Enabled static code analysis tool
> Added field alignment ordering, enabled static code analysis

- internal/app.go
Added version and commit to Agent startup log
> Agent version

- go.mod
- go.sum
- test/performance/go.mod
- test/performance/go.sum
- test/performance/vendor/github.com/rs/cors/README.md
- test/performance/vendor/github.com/rs/cors/cors.go
- test/performance/vendor/github.com/rs/cors/internal/sortedset.go
- test/performance/vendor/github.com/rs/cors/utils.go
- test/performance/vendor/modules.txt
- vendor/github.com/rs/cors/README.md
- vendor/github.com/rs/cors/cors.go
- vendor/github.com/rs/cors/internal/sortedset.go
- vendor/github.com/rs/cors/utils.go
- vendor/modules.txt
Updated version of github.com/rs/cors to v1.11.0
Closes 
https://github.com/nginx/agent/security/dependabot/55
https://github.com/nginx/agent/security/dependabot/56
> updated github.com/rs/cors version

- test/integration/utils/test_container_utils.go
Add integration test for checking Agent starts with correct version string
> Added version regex to parse the logs to see if matches vsemvar format

- test/integration/go.mod
- test/integration/vendor/modules.txt
Bumped the version of docker for https://github.com/nginx/agent/security/dependabot/57
> update docker version

- README.md
Add badges to v3 for Go version, license, contributions, and Slack channel
> Add badges to v3 for Go version, license, contributions, and Slack channel

- .github/workflows/v3-release.yml
> Update workflow permissions

- go.mod
- go.sum
- internal/collector/factories.go
- internal/collector/factories_test.go
> Remove file stats receiver

- .github/workflows/azure-upload.yml
Add a manual workflow to re-upload packages to Azure blob store
> Add manual Azure upload

- internal/watcher/health/health_watcher_service.go
- nginx-agent.conf
Change default log level to info
> Change default log level to info

- site/content/changelog.md
> Update website changelog for v2.37.0

- site/content/installation-upgrade/container-environments/docker-images.md
- site/content/installation-upgrade/installation-oss.md
PR to fix 2 broken URLs in NGINX-Agent Documentation
> Fix broken URLS in docs

- docs/architecture/config_apply.md
Fixed link from config apply to rollback 
> Fix link in config apply diagram

- api/grpc/mpi/v1/files.pb.go
- api/grpc/mpi/v1/files.proto
- docs/proto/protos.md
Updated documentation for the proto comments on certain fields
> generated new docs for the payload

- .github/workflows/docs-build-push.yml
Update docs-action workflow version. See [changelog](https://github.com/nginxinc/docs-actions/releases/tag/v1.0.3).
> Update docs-action workflow version

- site/content/installation-upgrade/installation-plus.md
Fix broken URL in /nginx-agent/installation-upgrade/installation-plus/
Ref: https://github.com/nginxinc/docs/issues/948
https://github.com/user-attachments/assets/44483d09-bdb6-494c-98de-32abb116e54c
> Update broken URL in installation-plus.md

- .github/workflows/ci.yml
> Change official integration tests to not run on fork

- site/go.mod
- site/go.sum
> (cherry-pick) Bump documentation theme version

- .github/workflows/ci.yml
Stop official image tests running on forks 
> Stop official image tests running on forks 

- site/go.mod
- site/go.sum
> Bump documentation theme version

- internal/collector/nginxplusreceiver/internal/metadata/generated_status.go
- test/integration/grpc_management_plane_api_test.go
Increase integration test retries
> Increase integration test retries

- scripts/docker/nginx-oss/deb/Dockerfile
> Fix debian oss image

- .github/workflows/docs-build-push.yml
This PR updates the docs-actions version.
This version of the docs-actions also includes auto-deploy support. Usage can be seen in the [caller example](https://github.com/nginxinc/docs-actions/tree/v1.0.4?tab=readme-ov-file#caller-example).
> Update docs-action to 1.0.4

- internal/collector/nginxplusreceiver/factory.go
- internal/collector/nginxplusreceiver/scraper.go
- internal/collector/otel_collector_plugin.go
Updated NGINX Plus receiver logging to use OTel collector logger
> Updated NGINX Plus receiver logging to use OTel collector logger

- .github/workflows/f5-cla.yml
- CONTRIBUTING.md
Adds the workflow that checks that contributors have signed the F5 CLA.
> Add CLA bot workflow

- scripts/docker/nginx-plus/debian/Dockerfile
- site/content/installation-upgrade/container-environments/docker-images.md
> Refactor docker images

- .github/workflows/ci.yml
> fix r30 pipeline failures

- .github/workflows/ci.yml
> remove r30 integration tests

- .github/workflows/f5-cla.yml
- CONTRIBUTING.md
Add CLA to v3 branch. I left the main references on purpose so when we switch v3 to main, won't forget to update
> Add CLA bot workflow (#828)

- internal/collector/nginxossreceiver/README.md
- internal/collector/nginxplusreceiver/README.md
Add README for NGINX OSS & Plus receivers
> Add README for NGINX OSS & Plus receivers

- .github/workflows/docs-build-push.yml
Bump docs-action to v1.0.5.
Adds support for latest hugo and nginx hugo theme version.
> Bump docs-action to v1.0.5

- .github/workflows/docs-build-push.yml
Cherry-pick bump docs-action to v1.0.5
> Cherry-pick bump docs-action to v1.0.5

- internal/collector/nginxossreceiver/internal/metadata/generated_status.go
- internal/collector/nginxplusreceiver/internal/metadata/generated_status.go
- test/config/nginx/nginx-with-server-block-access-log.conf
- test/integration/grpc_management_plane_api_test.go
Add file watcher and data plane status update integration test
> Add file watcher and data plane status update integration test

- .github/workflows/docs-build-push.yml
Add auto deployment from `main` to docs staging environment
> Add auto deployment from main to docs staging environment

- site/content/contribute/dev-environment-setup.md
- site/content/installation-upgrade/getting-started.md
> Fix broken links causing deployment failures

- .github/workflows/ci.yml
Just remove the if condition to run it. 
> Publish package condition update

- .github/workflows/ci.yml
- .github/workflows/release-branch.yml
- Temporarily stop publishing packages on v3 branch
- Fix version for signed packages in release workflow
> Temporarily stop publishing packages on v3 branch

- README.md
Update mdatagen install instructions in README.md
> Update mdatagen install instructions in README.md

- .github/workflows/ci.yml
Fix NGINX OSS integration tests
> Fix NGINX OSS integration tests

- site/config/docker/config.toml
- site/go.mod
- site/go.sum
- site/hugo-entrypoint.sh
Cherry pick [Fix docs docker failing without git context](https://github.com/nginx/agent/commit/3775b7993bb48e4031c6383697699108031cd013)
> [Cherry pick] Fix docs docker failing without git context

- site/content/installation-upgrade/container-environments/docker-images.md
Remove Dockerfiles link from **Build container images** page. 
> Remove link to github dockerfiles

- .github/workflows/ci.yml
> Remove extra bracket from build number

- README.md
- internal/collector/nginxossreceiver/internal/metadata/generated_resource_test.go
- internal/collector/nginxplusreceiver/internal/metadata/generated_resource_test.go
- test/mock/collector/README.md
- test/mock/grpc/README.md
Add instructions for the following to the README:
- Running unit tests
- Running integration tests
- Testing with mock management gRPC server 
- Testing with mock management OTel collector
> Add testing NGINX Agent section to README

- .github/workflows/ci.yml
> Add check that integration tests pass before making a release

- Makefile.packaging
Fail release job if packages fail to publish.
> Fail release job if packages fail to publish.

- .github/workflows/docs-build-push.yml
This will automatically deploy the docs from the `main` branch to production.
> Autodeploy main docs to production

- Makefile.packaging
Fail release job if packages fail to publish
> Fail release job if packages fail to publish

- test/docker/performance/Dockerfile
Update performance test Dockerfile to use NGINX R32
> Update performance test Dockerfile to use NGINX R32

- site/content/configuration/configuration-overview.md
- site/content/configuration/configure-nginx-agent-features.md
Add a new page that describes NGINX Agent features.
> Add a docs page to explain NGINX Agent features

- go.mod
- go.sum
Updated golang.org/x/net version
> Updated golang.org/x/net version

- internal/command/command_plugin.go
- internal/command/command_plugin_test.go
- internal/command/command_service.go
- internal/config/config.go
- internal/datasource/proto/response.go
- internal/file/file_manager_service.go
- internal/file/file_plugin.go
- internal/file/file_plugin_test.go
- internal/logger/logger.go
- internal/resource/nginx_plus_actions.go
- internal/resource/resource_plugin.go
- internal/watcher/instance/nginx_process_parser.go
- internal/watcher/watcher_plugin_test.go
- pkg/id/message.go
- pkg/id/message_test.go
- pkg/id/uuid.go
- pkg/id/uuid_test.go
- test/mock/grpc/mock_management_command_service.go
- test/mock/grpc/mock_management_file_service.go
> Add public id package

- test/integration/go.mod
- test/integration/vendor/modules.txt
- test/performance/go.mod
- test/performance/vendor/modules.txt
> Update agent sdk dependency

- test/performance/go.mod
- test/performance/vendor/modules.txt
Update performance test dependencies
> Update performance test dependencies

- .github/workflows/release-branch.yml
Package upload server url needs `https`
> add https:// to upload url

- .github/workflows/release-branch.yml
> Add GOPROXY on release jobs

- README.md
- Refactor the agent landing page to point to NGINX One
- Simplify the page
- Make better use of the official documentation 
> Update agent landing page and readme

- scripts/packages/preinstall.sh
Migrate instance group to config sync group during V2 to V3 upgrade
> Migrate instance group to config sync group during V2 to V3 upgrade

- .github/workflows/release-branch.yml
Remove GOPROXY from release branch workflow since it currently is failing the workflow.
> Remove GOPROXY from release branch workflow

- internal/collector/otelcol.tmpl
- test/config/collector/test-opentelemetry-collector-agent.yaml
- test/mock/collector/grafana/provisioning/dashboards/host-metrics.json
> Adds memory limit metrics

- Makefile.packaging
> Update APK package version

- go.mod
Update golang toolchain version to 1.23.8
> Update golang toolchain version to 1.23.8

- go.mod
Update golang toolchain to 1.23.8
> Update golang toolchain to 1.23.8

- src/core/metrics/metrics_util.go
- test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/metrics_util.go
> Merge v2.40.1 back to main

- internal/config/config.go
- test/config/agent/nginx-agent-otel-load.conf
- test/mock/collector/nginx-agent.conf
Clean up log level documentation
> Clean up log level documentation

- .github/workflows/release-branch.yml
- Makefile.packaging
- Modify tarball name to remove the `v3` suffix
- Add GOPROXY variable to `release-branch.yml`
- Modify apk package naming to match the established conventions of nginx oss (https://nginx.org/packages/mainline/alpine/)
> Agent v3: Release Packaging

- .github/workflows/ci.yml
Test is taking too long execute so removing for now.
> Remove Ubuntu 22.04 integration test

- internal/collector/nginxplusreceiver/scraper.go
- internal/collector/nginxplusreceiver/scraper_test.go
- internal/collector/nginxplusreceiver/testdata/expected.yaml
Fix request count metric for NGINX Plus receiver
> Fix request count metric for NGINX Plus receiver

- scripts/packages/postremove.sh
In the post remove script, removing the directories /etc/nginx-agent, /var/log/nginx-agent and /var/lib/nginx-agent
> Fix purging of dirs and files

- .github/workflows/codeql.yml
This PR updates CodeQL workflow. CodeQL will reference and use common workflow unified for all NGINX repositories.
> Update codeql workflow to use common codeql rules

- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- .github/workflows/label-pr.yml
- .github/workflows/release-branch.yml
- Update CodeQL workflow to use nginxinc/compliance-rules workflow
- Update permissions in workflows
> Update github workflows

- internal/file/file_manager_service.go
> Release 3.0.1

- go.mod
- internal/file/file_manager_service.go
- internal/file/file_manager_service_test.go
- internal/file/filefakes/fake_file_manager_service_interface.go
Reverts nginx/agent#1133
Need to not squash the commits next time
>  Revert "[Release 3.0.2] Merge back into main"

- go.mod
- internal/file/file_manager_service.go
- internal/file/file_manager_service_test.go
- internal/file/filefakes/fake_file_manager_service_interface.go
> [Release 3.0.2] Merge back into main

- go.mod
- sdk/go.mod
- test/integration/go.mod
- test/performance/go.mod
Bump golang version from 1.23.8 to 1.23.10.
> Bump golang version from 1.23.8 to 1.23.10

- .github/workflows/mend.yml
Add Mend workflow as part of the PtD initiative.
> Add mend workflow

- go.mod
- scripts/packages/preinstall.sh
Fix config format outputted by preinstall script.
> Fix config format outputted by preinstall script

- internal/datasource/config/nginx_config_parser_test.go
Add more unix socket unit tests.
> Add more unix socket unit tests

- test/docker/entrypoint.sh
> Add check for nginx pid file in test docker images

- internal/collector/otel_collector_plugin_test.go
> Fix Failing Unit-Test

- .github/workflows/release-branch.yml
> change runner to public

- .github/workflows/release-branch.yml
- Makefile.packaging
> Version fix

- .github/workflows/ci.yml
> Fix threshold values and typo in ci.yml

- internal/watcher/file/file_watcher_service.go
Add nil pointer check to file watcher.
> Add nil pointer check to file watcher

- internal/datasource/nginx/log_tailer.go
Fix how we handle log tailing when the line is nil.
> Fix how we handle log tailing when the line is nil
