nginx/agent

.github/workflows/release-branch.yml, scripts/packages/nginx-agent.service
* Fix agent package to link to GitHub docs instead of docs website.
* Fix release draft to link to same
=> Fix docs url to link to GitHub

Makefile.packaging
Fix architecture of arm apk packages
First noticed in pipeline runs:
```
/bin/sh: 3: [: aarch64: unexpected operator
using apk packager...
created package: ./build/packages/apk/v3.13/aarch64/nginx-agent-2.19.0.apk
using apk packager...
created package: ./build/packages/apk/v3.14/aarch64/nginx-agent-2.19.0.apk
using apk packager...
created package: ./build/packages/apk/v3.15/aarch64/nginx-agent-2.19.0.apk
using apk packager...
created package: ./build/packages/apk/v3.16/aarch64/nginx-agent-2.19.0.apk
/bin/sh: 3: [: x86_64: unexpected operator
using apk packager...
created package: ./build/packages/apk/v3.13/x86_64/nginx-agent-2.19.0.apk
using apk packager...
created package: ./build/packages/apk/v3.14/x86_64/nginx-agent-2.19.0.apk
using apk packager...
created package: …
```
=> Fix arch of apk packages

src/plugins/nginx.go
There is a case where the DPM sends an empty app_protect_metadata to erase the old meta when the user no longer uses NAP.
Check if app_protect_metadata's nap version is empty first before we compare the installed NAP version and the metadata NAP version and throw error.
=> fix: check if app_protect_metadata's nap version is empty first.

src/core/nginx.go, src/core/nginx_test.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/nginx.go, test/performance/vendor/github.com/nginx/agent/v2/src/plugins/nginx.go
In proc, if the process symlink path has `(deleted)`, it's an indication that the process was deleted. Since we already have binary change detection, this change deletes the "deleted" in the exec path, and trim out the "deleted" so the exec path is valid for the original binary, which could have an updated binary.
=> fix: detect nginx upgrade

.nfpm.yaml, scripts/.local-nfpm.yaml, scripts/packages/postinstall.sh
Updated the packaging configuration to do a config|noreplace. New configuration settings should get added into .rpmnew file after upgrade of package
=> Fix packaging config for 2.20

.nfpm.yaml, scripts/.local-nfpm.yaml, scripts/packages/preinstall.sh
Revert change to do a no replace on the conifg. Default config in the post install still exists until we get a working solution in nfpm.
=> rhel packages not to be replaced

src/plugins/nginx.go
There is a case where the DPM sends an empty app_protect_metadata to erase the old meta when the user no longer uses NAP.
Check if app_protect_metadata's nap version is empty first before we compare the installed NAP version and the metadata NAP version and throw error.
=> fix: check if app_protect_metadata's nap version is empty first. 

Makefile
Relatively small change to show help when `make` is issued without any explicit target.
Before:
```
% make
rm -rf ./build/packages
```
After:
```
% make
Usage:
help                      Show help message
all                       Compile and run code.
clean                     Remove build directory
run                       Run code
run-debug                 Run code
build                     Build agent executable
deps                      Update dependencies in vendor folders
lint                      Run linter
format                    Format code
install-tools             Install dependencies in tools.go
local-apk-package         Create local apk package
local-deb-package         Create local deb package
local-rpm-package         Create local rpm package
local-txz-package …
```
=> fix: reorder Makefile targets to made help the default

README.md, docs/content/getting-started.md, nginx-agent.conf
Remove the default gRPC configuration. This uses REST by default
=> WIP: Remove the default gRPC configuration for the nginx-agent

scripts/packages/nginx-agent
Updates the FreeBSD rc.d script to use the standard FreeBSD rc.subr template. This reduces the complexity of the file and fixes some errors that occurs when running `service nginx-agent restart`
```
freebsd@testenv-3dd5fc2a-data-1:~ $ sudo service nginx-agent restart
nginx_agent already running?  (pid=3902).
freebsd@testenv-3dd5fc2a-data-1:~ $ sudo service nginx-agent restart
cat: /var/run/nginx_agent.pid: No such file or directory
kill: illegal process id: 
freebsd@testenv-3dd5fc2a-data-1:~ $ echo $?
1
```
Updated script
```
freebsd@testenv-3dd5fc2a-data-1:~ $ sudo service nginx-agent restart
Stopping nginx_agent.
Waiting for PIDS: 4081, 4081.
Starting nginx_agent.
freebsd@testenv-3dd5fc2a-data-1:~ $ echo $?
0
```
Before creating a PR, run through this checklist and mark each as …
=> Update FreeBSD rc.d script

src/core/metrics/sources/nginx_plus.go
Logic check will fail if equal, appears to be a typo
=> Logic check will fail if equal condition

src/core/nginx.go, src/core/nginx_test.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/nginx_plus.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/nginx.go
- skip delete and log if intended delete file doesn't exists
- additional changes to tests
=> fix: skip delete if file doesn't exists

.github/workflows/ci.yml
There are currently errors being observed with the `golangci/golangci-lint-action` github action. The errors seem to be related to caching in the github action, so for now we will skip the caching until a fix is made to the github action.
=> Skip pkg cache for golangci/golangci-lint-action

go.mod, src/core/config/config.go, src/core/config/defaults.go, src/core/config/types.go, src/extensions/nginx-app-protect/nap/attack_signatures.go, src/extensions/nginx-app-protect/nap/attack_signatures_test.go, src/extensions/nginx-app-protect/nap/nap.go, src/extensions/nginx-app-protect/nap/nap_content.go, src/extensions/nginx-app-protect/nap/nap_content_test.go, src/extensions/nginx-app-protect/nap/nap_metadata.go, src/extensions/nginx-app-protect/nap/threat_campaigns.go, src/extensions/nginx-app-protect/nap/threat_campaigns_test.go, src/extensions/nginx-app-protect/nap/types.go, src/plugins/nginx.go, src/plugins/nginx_app_protect.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/config/config.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/config/defaults.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/config/types.go, test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/attack_signatures.go, test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/nap.go, test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/nap_content.go, test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/nap_metadata.go, test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/threat_campaigns.go, test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/types.go, test/performance/vendor/github.com/nginx/agent/v2/src/plugins/nginx.go, test/performance/vendor/github.com/nginx/agent/v2/src/plugins/nginx_app_protect.go
WIP: Add Agent support for pre-compiled NAP content published via an external source.
Support the publication of NGINX App Protect (NAP) pre-compiled content (policies and log profiles) from an external source. This is configurable via nginx-agent.conf:
`nginx_app_protect:
precompiled_publication: true/false`
true = Policies and Log Profiles are compiled and published from an external source (tgz files)
false = Policies and Log Profiles are compiled locally (json files)
=> Add Support for NAP Precompiled Publication

.github/workflows/release-branch.yml, Makefile.packaging, scripts/packages/packager/signed-entrypoint.sh
Created a new directory to store the packages that need to be uploaded to a github release.
The reason being is that some packages need to be renamed to avoid conflicts during the upload.
Example of github packages to be uploaded:
```
./build/github/packages/nginx-agent-2.21.0.el8.ngx.x86_64.rpm
./build/github/packages/nginx-agent-2.21.0-v3.13-aarch64.apk
./build/github/packages/nginx-agent-2.21.0.sles15.ngx.x86_64.rpm
./build/github/packages/nginx-agent-2.21.0.sles12.ngx.x86_64.rpm
./build/github/packages/nginx-agent-2.21.0-v3.15-aarch64.apk
./build/github/packages/nginx-agent-2.21.0~bionic_amd64.deb
./build/github/packages/nginx-agent-2.21.0~buster_arm64.deb
./build/github/packages/nginx-agent-2.21.0~bullseye_arm64.deb
./build/github/packages/nginx-agent-2.21.0-v3.15-x86_64.apk …
```
=> Update release workflow package upload

src/extensions/nginx-app-protect/nap/nap_metadata.go, src/extensions/nginx-app-protect/nap/nap_metadata_test.go, test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/nap_metadata.go
When processing NAP metadata for potential changes, the case when the NAP metadata doesn't exist wasn't handled.
Added unit test too.
Fix: Don't return an error when the `app_protect_metadata.json` file doesn't exist, continue processing to create the file.
Added a unit test to verify fix.
=> fix: Handle case when NAP metadata doesn't exist

src/extensions/nginx-app-protect/nap/nap_metadata.go, src/extensions/nginx-app-protect/nap/nap_metadata_test.go, test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/nap_metadata.go
When writing NAP metadata, create the metadata directory if it doesn't exist.
- Create NAP metadata directory if it doesn't already exist
- Expanded unit test to cover this case
=> fix: Handle case when NAP metadata directory doesn't exist

Makefile, scripts/docker/nginx-oss/entrypoint.sh, scripts/docker/nginx-oss/ubuntu/Dockerfile, test/integration/api/api_test.go, test/integration/api/docker-compose.yml, test/integration/go.mod
Moved Dockerfile for integration tests from `./test/docker/integration/api`  **=>** `./scripts/docker/nginx-oss/ubuntu`
=> Move Dockerfile to Folder for OSS

Makefile, Makefile.containers, Makefile.packaging, scripts/docker/nginx-oss/ubuntu/Dockerfile, scripts/docker/nginx-plus/alpine/Dockerfile, scripts/docker/nginx-plus/amazonlinux/Dockerfile, scripts/docker/nginx-plus/centos/Dockerfile, scripts/docker/nginx-plus/debian/Dockerfile, scripts/docker/nginx-plus/oraclelinux/Dockerfile, scripts/docker/nginx-plus/redhatenterprise/Dockerfile, scripts/docker/nginx-plus/suse/Dockerfile, scripts/docker/nginx-plus/ubuntu/Dockerfile, scripts/packages/packager/Dockerfile, test/integration/api/api_test.go, test/integration/api/docker-compose.yml
This change introduces an ability to use [podman](https://podman.io) container management tool in addition to docker, which remains the default. Podman provides daemonless architecture and allows to run containers in unprivileged mode natively on Linux.
On systems with both docker and podman installed, the `CONTAINER_CLITOOL` environment variable can be used to choose a desired option.
Platform / versions, Docker:
```
Host - MacOS on M1 pro
% sw_vers 
ProductName:	macOS
ProductVersion:	12.6.1
BuildVersion:	21G217
% docker version
Client:
Cloud integration: v1.0.29
Version:           20.10.21
API version:       1.41
Go version:        go1.18.7
Git commit:        baeda1f
Built:             Tue Oct 25 18:01:18 2022 …
```
=> feat: podman support

scripts/packages/packager/local-entrypoint.sh, scripts/packages/packager/signed-entrypoint.sh
Add temporary fix for detected dubious ownership git issue when building freebsd packages
See here for more info: https://github.com/actions/checkout/issues/1169
=> Add temporary fix for detected dubious ownership git issue when building freebsd packages

hugo/content/getting-started.md, hugo/content/installation.md
Based on the changes from https://github.com/nginx/agent/pull/208
Move the Go installation step to a different section.
=> fix: move go installation step

src/core/environment.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/environment.go
Update Processes function to only add the exe path for nginx master processes and to leave it empty for nginx worker processes
=> Fix error reading exe process information

README.md, hugo/content/installation.md
Since the release of https://github.com/nginx/agent/releases/tag/v2.22.0 and onwards we have offered individual packages rather than `nginx-agent.tar.gz` containing all available packages.
* Update readme and installation doc to reference individual packages rather than tar file.
=> Fix docs to reference packages in current release

src/core/nginx.go, src/plugins/nginx.go
This PR changes the `log.traceF` and `log.debugF` function arguments in those cases where we log the `NginxConfig` protobuf message. Instead of the raw message (which is harder to parse and read when doing troubleshooting), the JSON version of the object is now logged.
Closes #209 
=> Print NginxConfig in JSON format for debug and trace levels

main.go
Include the current version in GRPC metadata, trimming the leading "v" to match common [RFC9110 `User-Agent`][1] conventions.
Before this change, the metadata `user-agent` contained `["go-grpc/1.52.0"]`. After this patch, it contains `["nginx-agent/2.23.1", "go-grpc/1.52.0"]`
[1]: https://httpwg.org/specs/rfc9110.html#field.user-agent
=> Send agent version in grpc metadata

src/core/nginx.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/nginx.go
Remove information from trace logging level for configuration push
=> remove fields from trace logging

Makefile
Previously `make build` did not do anything if a binary was deleted from the `build` directory, or the directory was created before running the target, as the target was not marked as PHONY:
```
% make clean
rm -rf ./build
% make build
GOWORK=off CGO_ENABLED=0 go build -ldflags="-w -X main.version=v2.23.1 -X main.commit=7a08fe56 -X main.date=2023-03-10_18-46-36" -o ./build/nginx-agent
% make build
make: `build' is up to date.
% rm build/nginx-agent 
% make build
make: `build' is up to date.
% ls -l build 
total 0
```
After the change:
```
% make clean
rm -rf ./build
% make build
GOWORK=off CGO_ENABLED=0 go build -ldflags="-w -X main.version=v2.23.1 -X main.commit=efc82b89 -X main.date=2023-03-10_19-53-49" -o ./build/nginx-agent
% make build
make: Nothing to be done for `build'.
% rm …
```
=> fix: made build target to work predictably

.github/workflows/ci.yml, test/integration/install/install_uninstall_test.go
* Install/uninstall test now uses a single context
* Fix: Check for nginx install now checks inside container rather than host
Passed 45 runs in a row on my VM 15 * matrix of `rockylinux`, `almalinux`, `ubuntu`(respectively):
```
Run 1 times
ok  	github.com/nginx/agent/test/integration/install	101.312s
ok  	github.com/nginx/agent/test/integration/install	94.418s
ok  	github.com/nginx/agent/test/integration/install	22.826s
Run 2 times
ok  	github.com/nginx/agent/test/integration/install	52.023s
ok  	github.com/nginx/agent/test/integration/install	33.253s
ok  	github.com/nginx/agent/test/integration/install	22.226s
Run 3 times
ok  	github.com/nginx/agent/test/integration/install	48.382s
ok …
```
=> Fix flaky install/uninstall test

sdk/proto/events/event.proto, src/core/nginx.go, test/integration/vendor/github.com/nginx/agent/sdk/v2/proto/events/event.proto, test/performance/vendor/github.com/nginx/agent/sdk/v2/proto/events/event.proto, test/performance/vendor/github.com/nginx/agent/v2/src/core/nginx.go, vendor/github.com/nginx/agent/sdk/v2/proto/events/event.proto
Add check if there are any warnings in the NGINX config validation
=> Add check if there are any warnings in the NGINX config validation

src/core/environment.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/environment.go
* The `exec.Command()` function was being passed an incorrect argument instead of the actual command to be executed
* Ran `go test` from within `src/core`
=> fix: Pass correct variable for lscpu command to work

src/plugins/nginx.go, test/performance/vendor/github.com/nginx/agent/v2/src/plugins/nginx.go
If multiple error logs are configured, the NGINX Agent wasn't waiting to get a message in the logErrorChannel for all the error log files. This caused an error in the agent when when it was trying to put a message onto a closed channel. Noe the agent will wait until it received a message for each error log before closing the channel. 
=> Update NGINX monitor function to handle monitoring multiple NGINX error logs

src/plugins/nginx.go, src/plugins/nginx_test.go, test/performance/vendor/github.com/nginx/agent/v2/src/plugins/nginx.go
Remove the pids draining feature from the post config apply workflow
=> remove pids draining

src/core/network/network.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/network/network.go
* use nstat -az
* fix #277 partially
=> Support GetNetOverflow in linux

sdk/backoff_test.go, sdk/certificates.go, sdk/config_apply.go, sdk/config_apply_test.go, src/core/nginx.go, src/core/nginx_test.go, test/integration/vendor/github.com/nginx/agent/sdk/v2/certificates.go, test/integration/vendor/github.com/nginx/agent/sdk/v2/config_apply.go, test/performance/vendor/github.com/nginx/agent/sdk/v2/certificates.go, test/performance/vendor/github.com/nginx/agent/sdk/v2/config_apply.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/nginx.go, vendor/github.com/nginx/agent/sdk/v2/certificates.go, vendor/github.com/nginx/agent/sdk/v2/config_apply.go
Fixes: https://github.com/nginx/agent/issues/184
* Handle special value `"off"` for disabling access logging for a given context. No longer erroneously produces a warning.
* Remove note in logs about disabled [`error_log`](https://nginx.org/en/docs/ngx_core_module.html#error_log). `error_log off;` does not disable error logging, this config produces an `error_log` in a file named `off`.
=> Fix handing of setting access_log off;

nginx-agent.conf, scripts/packages/manifest, scripts/packages/postinstall.sh, scripts/packages/preinstall.sh, scripts/selinux/README.md
Removing 5 seconds sleep at install time (preinstall script)
Updated the use of the words unified agent and agent to NGINX Agent
=> Packages scripts refactor

.github/workflows/ci.yml
* Skips CI for changes to:
* Hugo docs
* Markdown/Github docs
* https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths
* https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#patterns-to-match-file-paths
=> Skip CI for docs only changes

scripts/packages/packager/local-entrypoint.sh, scripts/packages/packager/signed-entrypoint.sh
* postremove.sh should be assigned +POST_DEINSTALL literally.
=> Fix packager script post deinstall.

.gitignore, Makefile, scripts/docker/nginx-plus/debian/Dockerfile
Bullseye docker image was not working. Updated the gnupg dependency
=> fixed bullseye docker image

docs/proto/events.md, sdk/proto/events/event.pb.go, sdk/proto/events/event.proto, test/integration/vendor/github.com/nginx/agent/sdk/v2/proto/events/event.pb.go, test/integration/vendor/github.com/nginx/agent/sdk/v2/proto/events/event.proto, test/performance/vendor/github.com/nginx/agent/sdk/v2/proto/events/event.pb.go, test/performance/vendor/github.com/nginx/agent/sdk/v2/proto/events/event.proto, vendor/github.com/nginx/agent/sdk/v2/proto/events/event.pb.go, vendor/github.com/nginx/agent/sdk/v2/proto/events/event.proto
Add documentation about each of the fields in the SecurityViolationEvent message.
=> doc: add comments for each field in the SecurityViolationEvent proto definition

sdk/grpc/grpc.go, src/core/config/commands.go, src/core/config/config.go, src/core/environment_test.go, src/core/network/network.go, src/extensions/nginx-app-protect/nap/attack_signatures.go, src/extensions/nginx-app-protect/nap/nap_metadata_test.go, src/extensions/nginx-app-protect/nap/threat_campaigns.go, src/plugins/agent_api_test.go, src/plugins/file_watcher_test.go, test/integration/reader_test.go, test/integration/vendor/github.com/nginx/agent/sdk/v2/grpc/grpc.go, test/performance/vendor/github.com/nginx/agent/sdk/v2/grpc/grpc.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/config/commands.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/config/config.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/network/network.go, test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/attack_signatures.go, test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/threat_campaigns.go, test/performance/vendor/github.com/nginx/agent/v2/test/utils/symbols.go, test/performance/vendor/github.com/nginx/agent/v2/test/utils/tls.go, test/utils/symbols.go, test/utils/tls.go, vendor/github.com/nginx/agent/sdk/v2/grpc/grpc.go
This change removes the usage of most of the deprecated APIs by changing them to the current APIs.
=> chore: update deprecated API calls

src/core/metrics/sources/disk.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/disk.go
Fixes #328
This change adds the mount point that failed to the disk usage error message.
=> Output mount point in error message

main.go
Fixes #334
This change prevents agent from having a segmentation fault when it receives a TERM or INT signal.
In this change, we add an explicit nil check for `cmder` in `main.go` around line 133. This prevents the condition where agent segfaults.
=> fix: fixes segfault when process is TERMed

src/core/network/network.go, src/core/network/network_test.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/network/network.go
Fixes #317
This fix resolves a problem where the header line of /proc/net/route is skipped twice when running on Linux. This change also adds error checking to the Scanner performing the parsing operation.
=> fix: fix Linux default network interface parsing

README.md, hugo/content/getting-started.md
Adding the Go 1.19.9 or higher version which should be used before building docker images to resolve stdlib CVE
=> Update Go version

main.go, sdk/proto/events/event.proto, src/core/nginx.go, test/integration/vendor/github.com/nginx/agent/sdk/v2/proto/events/event.proto, test/performance/vendor/github.com/nginx/agent/sdk/v2/proto/events/event.proto, test/performance/vendor/github.com/nginx/agent/v2/src/core/nginx.go, vendor/github.com/nginx/agent/sdk/v2/proto/events/event.proto
nginx-agent, when being stopped by sending SIGTERM (default way of stopping a service), closes all opened streams with RST_STREAM with error code 0x8 (CANCEL) (https://httpwg.org/specs/rfc7540.html#ErrorCodes ), which leads to extra warnings and inability to track actual response codes in nginx proxy layer.
With these changes, when the agent will receive the SIGTERM signal the controller will be closed before exiting.
=> Close controller before exiting

src/core/nginx.go, src/core/nginx_test.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/nginx.go
Fixes #185
This change suppresses the warning messages emitted when nginx is configured to output logs to `STDOUT`, `STDERR`, or syslog.
=> Skip warnings on non-file log destinations

sdk/config_helpers.go, sdk/config_helpers_test.go, test/integration/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go, test/performance/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go, vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
Changed the way we parse plus and stub status from configs so it works with :port and port only formats. Also parse = in location block. 
=> added fix for listen directives in stub status and plus API configs

sdk/config_helpers.go, sdk/config_helpers_test.go, test/integration/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go, test/performance/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go, vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
Fixed: #340 
* nginx has the predefined access log format below.
* https://nginx.org/en/docs/http/ngx_http_log_module.html
* if the log_format isn't specified or combined, it should be predefined one.
=> Fix: specified predefined access log format (#340)

hugo/content/uninstall.md
Adding NGINX Agent uninstall doc for each operating system
=> Add NGINX Agent Uninstall Doc

hugo/go.mod
Update documentation go.mod to use latest hugo theme 0.33.0
- Fixes Coveo search
=> fix: bump hugo theme to 0.33.0

src/core/metrics/sources/nginx_access_log.go, src/core/metrics/sources/nginx_access_log_test.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/nginx_access_log.go
This PR aims to fix the bug where if a user has an access log format with a variable that is not present in the `logVarMap` https://github.com/nkashiv/agent/blob/main/src/core/metrics/sources/nginx_access_log.go#L33 then the access log parsing fails and no access log metric is collected. 
For example, the following log format will cause an error because it contains `$upstream_addr` which is not present in the map. A user can also have a custom variable defined which will break the parsing. 
```
log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
'$status $body_bytes_sent "$http_referer" '
'"$http_user_agent" "$http_x_forwarded_for" '
'"$upstream_addr" "$upstream_response_time" "$upstream_status" '
'$http_x_amplify_id';
```
Added a unit test in …
=> Fix access log parsing for custom log format

sdk/config_apply.go, sdk/config_apply_test.go, sdk/config_helpers.go, sdk/config_helpers_test.go, src/core/config/config.go, src/core/config/defaults.go, src/core/config/types.go, src/core/environment_test.go, src/core/nginx.go, src/extensions/nginx-app-protect/nap/nap_metadata.go, src/extensions/nginx-app-protect/nap/nap_metadata_test.go, src/plugins/agent_api.go, src/plugins/metrics.go, src/plugins/nginx.go, src/plugins/nginx_test.go, test/integration/vendor/github.com/nginx/agent/sdk/v2/config_apply.go, test/integration/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go, test/performance/vendor/github.com/nginx/agent/sdk/v2/config_apply.go, test/performance/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/config/config.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/config/defaults.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/config/types.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/nginx.go, test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/nap_metadata.go, test/performance/vendor/github.com/nginx/agent/v2/src/plugins/agent_api.go, test/performance/vendor/github.com/nginx/agent/v2/src/plugins/metrics.go, test/performance/vendor/github.com/nginx/agent/v2/src/plugins/nginx.go, vendor/github.com/nginx/agent/sdk/v2/config_apply.go, vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
=> Ignore directives feature

test/integration/utils/test_container_utils.go
* Add timeout to integration test setup. Test will now fail after 20 seconds if it cannot start agent service rather than default of 10 minutes.
=> Add timeout to integration tests setup

src/core/metrics/sources/nginx_worker.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/nginx_worker.go
Add validation that pid integer is a 32 bit integer
=> Fix integer overflow

src/core/metrics/sources/nginx_worker.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/nginx_worker.go
Use ParseInt instead of Atoi when converting process id string to an int
=> Use ParseInt instead of Atoi when converting process id string to an int

sdk/config_helpers.go, sdk/config_helpers_test.go, src/core/metrics/sources/nginx_access_log.go, src/core/tailer/tailer.go, src/core/tailer/tailer_test.go, test/integration/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go, test/performance/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/nginx_access_log.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/tailer/tailer.go, vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
* The many nginx's users choice the log format into Labeled Tab Separated Values to be able to analyze and  extend logs more easily.
* So, it should be support this format that the user can be more easily to switch from conventional log collector to nginx-agent.
=> Support ltsv

src/core/metrics/sources/net_io.go, src/core/metrics/sources/net_io_test.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/net_io.go
- Allow loopback interface metrics in a metric report sent to backend server.
- Add tests.
=> Populate loopback interface metrics to a metric report

src/core/nginx.go, src/core/nginx_test.go, src/plugins/nginx.go, src/plugins/nginx_test.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/nginx.go, test/performance/vendor/github.com/nginx/agent/v2/src/plugins/nginx.go
Monitor NGINX logs for critical & error after an NGINX reload
=> Monitor NGINX logs for critical & error messages after NGINX reload 

.github/workflows/ci.yml
Set go version for integration tests to 1.19.10 to fix pipeline 
Pipeline was broken due to the following security fix in go 1.20.6 & 1.19.11 https://groups.google.com/g/golang-announce/c/2q13H6LEEx0
=> fix pipeline

Makefile
Use OSARCH variable build amd64 binaries on arm64
=> quick change to use OSARCH variable to build amd64 binaries on arm64

.github/workflows/ci.yml, scripts/packages/packager/local-entrypoint.sh, scripts/packages/packager/signed-entrypoint.sh
This change allows to get working FreeBSD agent packages on both x86 and arm64 hosts/runners when running `make local-txz-package` target.
=> fix: use host architecture to determine FreeBSD ABI

src/plugins/nginx.go, src/plugins/nginx_test.go, test/performance/vendor/github.com/nginx/agent/v2/src/plugins/nginx.go
If an error is detected after a NGINX reload during a config apply, then we need to rollback the config changes and reload NGINX again to revert the changes.
=> Reload NGINX after rolling back NGINX configuration changes

sdk/config_helpers.go, sdk/config_helpers_test.go, test/integration/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go, test/performance/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go, vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
Updated `parseAddressesFromServerDirective` function to return multiple possible addresses.
See here for more info on the listen directive http://nginx.org/en/docs/http/ngx_http_core_module.html#listen
=> Update how the SDK parses NGINX API server directive

src/core/metrics/sources/nginx_access_log.go, src/core/metrics/sources/nginx_access_log_test.go, src/core/metrics/sources/nginx_error_log.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/nginx_access_log.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/nginx_error_log.go
Update nginx access & error log metric sources to only report metrics that are available instead of returning zero for metrics that are missing.
=> Update nginx access & error log metric sources to only report metrics that are available

sdk/client/commander.go, sdk/client/metric_reporter.go, test/integration/vendor/github.com/nginx/agent/sdk/v2/client/commander.go, test/integration/vendor/github.com/nginx/agent/sdk/v2/client/metric_reporter.go, test/performance/vendor/github.com/nginx/agent/sdk/v2/client/commander.go, test/performance/vendor/github.com/nginx/agent/sdk/v2/client/metric_reporter.go, vendor/github.com/nginx/agent/sdk/v2/client/commander.go, vendor/github.com/nginx/agent/sdk/v2/client/metric_reporter.go
Improve error logging for gRPC EOF errors.
=> Improve error logging for gRPC EOF errors

hugo/config/_default/config.toml, hugo/go.mod, hugo/go.sum
- Bumps the Hugo theme to v.0.35.0
- New highlight colors for code blocks that fix some accessibility issues
=> fix: bump hugo theme to 0.35.0

sdk/config_helpers.go, sdk/config_helpers_test.go, test/integration/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go, test/performance/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go, vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
Add support for the `ssl_client_certificate` and `ssl_trusted_certificate` directives to treat them the same as `ssl_certificate` and `ssl_proxy_certificate`.  Certificates managed in NMS can then appropriately display the associations for NGINX Instance and Instance Groups when configured.
This change is required to complete the expected end-to-end behavior of NMS-43701.
=> chore: cert directives for ssl_client_certificate and ssl_trusted_certificate

sdk/config_helpers.go, sdk/config_helpers_test.go, src/core/nginx.go, test/integration/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go, test/integration/vendor/github.com/nginx/agent/v2/src/core/nginx.go, test/performance/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/nginx.go, vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
Fix how status API URL is determined when both stub status and NGINX Plus APIs are configured.
=> Fix how status API URL is determined when both stub status and NGINX Plus APIs are configured

src/plugins/nginx.go, test/performance/vendor/github.com/nginx/agent/v2/src/plugins/nginx.go
Fix intermittent issue where the `reloadNginx` function never finishes
=> Fix intermittent issue where the reloadNginx function never finishes

sdk/config_helpers.go, test/integration/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go, test/performance/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
- From the NGINX UI, was unable to publish config changes for an instance when a `.conf` file was created under `/etc/nginx/conf.d`. The absolute path used to update the config changes contain variables with `$` (e.g., `/etc/nginx/$variable_name)` and a `No such file or directory` error occurred.
- Agent log showed errors related to parsing the nginx config files using an absolute path that contains variables.
```
time="2023-08-16T17:26:14Z" level=info msg="Upload sending done e0991342-0956-430a-a4f5-ece28395c421 (chunks=2)"
time="2023-08-16T17:38:42Z" level=warning msg="Error unable to add file watcher for /etc/nginx/conf.d/.config1.conf.swx : stat /etc/nginx/conf.d/.config1.conf.swx: no such file or directory"
time="2023-08-16T17:38:42Z" level=error msg="Error occurred adding watcher …
```
=> fix: fix logic for parsing absolute path to nginx config file

sdk/config_helpers.go, sdk/config_helpers_test.go, test/integration/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go, test/performance/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go, vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
Improve status API detection and validation.
=> Improve status API detection and validation

src/core/nginx.go, test/integration/vendor/github.com/nginx/agent/v2/src/core/nginx.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/nginx.go
- ensures full path when doing file operation using directory map, this is consistent with previous assumptions
=> fix: ensure fullpath

Makefile
If someone forks just the main branch of the repo, they wont have any tags in their forked repo.
To fix this we should query the github api to get the latest tag. That way when someone builds a package it will have a valid version number instead of it being blank.
=> Fix version for forked repo

src/core/nginx.go, test/integration/vendor/github.com/nginx/agent/v2/src/core/nginx.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/nginx.go
Add error log if duplicate NGINX IDs are found due to multiple NGINX instances running.
=> Add error log if duplicate NGINX IDs are found

src/extensions/nginx-app-protect/nap/attack_signatures.go, src/extensions/nginx-app-protect/nap/attack_signatures_test.go, src/extensions/nginx-app-protect/nap/threat_campaigns.go, src/extensions/nginx-app-protect/nap/threat_campaigns_test.go, test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/attack_signatures.go, test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/threat_campaigns.go
The format of "/opt/app_protect/var/update_files/signatures/signature_update.yaml" from the latest Attack Signature update (2023.10.04) contained additional items.
Changed the parsing of the yaml file to not be "strict" to maintain compatibility across versions.
=> fix: Tolerate additional fields in App Protect yaml files

README.md, src/core/metrics/sources/nginx_plus.go, src/core/metrics/sources/nginx_plus_test.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/nginx_plus.go
`plus.worker.conn.idle`, `plus.worker.conn.active` and `plus.worker.http.request.current` are `avgs` but were being treated like `sums` when converting to `simpleMetrics`  in `nginx_plus.go`
Removed calculation of `stats - prevStats` from `conn.idle`, `conn.active` and `http.request.current`
Added note about Agent showing up as a connection in `plus.worker.conn.idle` or `plus.worker.conn.active`
=> fix worker metrics

sdk/client/commander.go, test/integration/vendor/github.com/nginx/agent/sdk/v2/client/commander.go, test/performance/vendor/github.com/nginx/agent/sdk/v2/client/commander.go, vendor/github.com/nginx/agent/sdk/v2/client/commander.go
Adding a retry lock so that if the commander client reconnects after a failure, that it will only attempt to reconnect once.
=> Add commander retry lock

src/core/grpc.go, test/integration/vendor/github.com/nginx/agent/v2/src/core/grpc.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/grpc.go
Fix user agent request header to have the correct agent version
=> Fix user agent request header to have the correct agent version

scripts/docker/nginx-plus/alpine/Dockerfile
`alpine>=v3.17` upgrades openssl version `v1.1.1w` -> `v3.0.x` which brings a slight format change which broke key verification.
```
$ openssl rsa -pubin -in /tmp/nginx_signing.rsa.pub -text -noout
RSA Public-Key: (2048 bit)
Modulus:
00:fe:14:f6:0a:1a:b8:86:19:fe:cd:ab:02:9f:58:
...
```
```
$ openssl rsa -pubin -in /tmp/nginx_signing.rsa.pub -text -noout
Public-Key: (2048 bit)
Modulus:
00:fe:14:f6:0a:1a:b8:86:19:fe:cd:ab:02:9f:58:
...
```
* Update expected key to match `openssl=v3.0.x` format
* Add sed replace to make old output format verify successfully against new key
* Add note so sed can be easily and safely removed in the future
=> Fix alpine plus dockerfile on alpine>=3.17

src/core/environment.go, test/integration/vendor/github.com/nginx/agent/v2/src/core/environment.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/environment.go
* Restrict permissions of config apply directory `755` -> `750`
=> Restrict config apply directory permissions

hugo/makefile
This updates the docs Makefile to run hugo and markdownlint via docker if local executables aren't available.
Changes are made _only_ in docs Makefile.
=> docs: add docker fallback for hugo and markdownlint

src/extensions/nginx-app-protect/nap/nap.go, src/extensions/nginx-app-protect/nap/nap_metadata.go, src/extensions/nginx-app-protect/nap/nap_metadata_test.go, src/extensions/nginx-app-protect/nap/nap_test.go, src/extensions/php_fpm_metrics.go, src/extensions/php_fpm_metrics_test.go, src/extensions/prometheus-metrics/prometheus_exporter.go, src/extensions/prometheus-metrics/prometheus_exporter_test.go, test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/nap.go, test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/nap_metadata.go, test/performance/vendor/github.com/nginx/agent/v2/src/extensions/php_fpm_metrics.go, test/performance/vendor/github.com/nginx/agent/v2/src/extensions/prometheus-metrics/prometheus_exporter.go
* Restrict permissions of NAP directories and files
* Improve error handling of NAP extension
* Lint
=> Restrict NAP file/dir permissions

hugo/content/upgrading.md
Update upgrade documentation based on the change in behaviour introduced by this PR https://github.com/nginx/agent/pull/352
=> Update upgrade documentation

site/content/configuration/configuration-overview.md, site/content/configuration/configure-nginx-agent-group.md, site/content/configuration/encrypt-communication.md, site/content/installation-upgrade/container-environments/docker-images.md, site/content/installation-upgrade/container-environments/docker-support.md, site/content/technical-specifications.md, site/go.mod, site/go.sum
- Moves some Agent docs formerly in the NMS section of the docs to the Agent product section of the docs.
- Various Doc refinements
- 
=> feat: move NMS agent docs

site/content/installation-upgrade/container-environments/docker-images.md
Adds the Documentation Catalog ID to a recent document.
=> fix: add missing catalog entry

site/content/installation-upgrade/container-environments/docker-images.md, site/content/technical-specifications.md
The information in this doc was originally added to the NMS docs, in the agent section, in [PR 210](https://github.com/nginxinc/docs/pull/210) in the docs repo.
I have made an effort to ensure the information provided here aligns with the current state of the Makefile in the repo. 
**Please verify that the supported distributions listed for OSS and Plus are correct, and that the location where the crt and key files should be saved is correct.**
=> Restore agent container information from nms docs 

site/content/installation-upgrade/container-environments/docker-images.md
Corrects the steps to build the official Alpine-based Agent images.
Adds a note about building images for unsupported OSs
=> feat: improve docker docs

internal/datasource/config/config_writer.go, internal/service/config_service.go, internal/service/config_service_test.go
Changes: 
- If there is no cache rollback will now fail
- If updating the cache during the final steps of a config apply fails, config apply no longer rolls back instead an error is logged and its considered a successful config apply 
=> Fixes to Rollback

src/core/environment.go
- Add additional check to detect non-docker container runtime during instance registration
- This function is a duplicate function and will be removed in a future release
=> fix: add additional container checks during instance registration

site/content/changelog.md
Adds the 2.32.2 release to the changelog at docs.nginx.com.
=> chore: Add the 2.32.2 Changelog to the docs website

.nfpm.yaml, test/integration/vendor/github.com/nginx/agent/v2/src/core/environment.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/environment.go
Update `nfpm.yaml` for apk packages to match the `scripts/.local-nfpm.yaml`
=> Fix  nfpm.yaml for apk packages

src/core/environment.go, src/core/environment_test.go, test/integration/vendor/github.com/nginx/agent/v2/src/core/environment.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/environment.go
Fix failing unit test by mocking IsContainer properly
=> fix unit test

sdk/config_helpers.go, test/integration/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go, test/performance/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go, vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
- Add logging to NGINX API http requests
- Increase http client timeout
=> Add logging to NGINX API http requests

Makefile, internal/logger/logger.go, internal/logger/logger_test.go, test/mock/grpc/cmd/main.go, test/mock/grpc/mock_management_plane_grpc_file_server.go
Add default temp config directory for mock management plane grpc file server
=> Add default temp config directory for mock management plane grpc file server

site/content/changelog.md
Adds 2.33.0 Release notes to docs.nginx.com
=> chore: add 2.33.0 changelog

internal/backoff/backoff.go, internal/plugin/grpc_client_plugin.go, internal/plugin/grpc_client_plugin_test.go
Need to check that the gRPC client is connected before sending a data plane status update
=> Fix send data plane status update nil pointer exception

site/content/configuration/connect-management-plane.md
Adds the `Connect to management plane` document
=> feat: add management plane connect doc

internal/service/instance/nginx_instance_service.go, internal/service/instance/nginx_instance_service_test.go, test/protos/instances.go
The version sent for a NGINX Plus Instance currently in the instance meta looks like `version: nginx-plus-r30-p2` when it should also contain the NGINX version `1.25.3 (nginx-plus-r31-p1)`
=> Fix NGINX Plus Instance, NGINX Version

internal/plugin/grpc_client_plugin_test.go
Increasing plugin test coverage as a fix for the coverage failing randomly by a few percent 
Added ProcessRequest unit test 
=> Increase plugin test coverage

Makefile
Added `MOCK_MANAGEMENT_PLANE_GRPC_ADDRESS` and `MOCK_MANAGEMENT_PLANE_API_ADDRESS` to make file and to `run-mock-management-grpc-server` make target so ports can be set and not change each time the mock management plane is run. 
Default has not changed, is set to `127.0.0.1:0` in the make file
=> Add api and grpc port to mock management plane make target

src/core/environment.go, test/integration/vendor/github.com/nginx/agent/v2/src/core/environment.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/environment.go
Remove temporary code since the following PR has been merged https://github.com/shirou/gopsutil/pull/1428
=> Remove unnecessary freebsd logic for finding process executable

sdk/checksum/checksum.go, sdk/checksum/checksum_test.go, test/integration/vendor/github.com/nginx/agent/sdk/v2/checksum/checksum.go, test/performance/vendor/github.com/nginx/agent/sdk/v2/checksum/checksum.go, vendor/github.com/nginx/agent/sdk/v2/checksum/checksum.go
Add additional checks in chunking functionality
=> Add additional checks in chunking functionality

site/content/configuration/configuration-overview.md, site/content/installation-upgrade/container-environments/docker-images.md
This commit changes the list of NGINX Agent variables to a table showing how it maps to the CLI flags, with an exception for the variable that doesn't have a flag yet. It links to the CLI flag section so that the reader can view the descriptions for additional context.
=> Change environment variable list to table with CLI references

scripts/docker/nginx-oss/rpm/Dockerfile, src/plugins/agent_api.go, src/plugins/agent_api_test.go, test/performance/vendor/github.com/nginx/agent/v2/src/plugins/agent_api.go
Example:
```
{
"status": "PENDING",
"checks": [
{
"name": "registration",
"status": "OK"
},
{
"name": "commandConnection",
"status": "OK"
},
{
"name": "metricsConnection",
"status": "PENDING"
}
]
}
```
=> Add pending health status

sdk/client/metric_reporter.go, test/integration/vendor/github.com/nginx/agent/sdk/v2/client/metric_reporter.go, test/performance/vendor/github.com/nginx/agent/sdk/v2/client/metric_reporter.go, vendor/github.com/nginx/agent/sdk/v2/client/metric_reporter.go
Fix metrics reporter retry logic
=> Fix metrics reporter retry logic

main.go, src/core/config/config.go, src/core/config/config_test.go, src/core/config/defaults.go, test/integration/vendor/github.com/nginx/agent/v2/src/core/config/config.go, test/integration/vendor/github.com/nginx/agent/v2/src/core/config/defaults.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/config/config.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/config/defaults.go
Agent now uses NGINX_AGENT as its environment prefix as opposed to NMS. If the old prefix is used, Agent migrates the value to the correct key and a message is logged warning the user to switch to the new prefix
=> Change environment prefix from nms to nginx_agent

site/content/configuration/configuration-overview.md, site/content/configuration/encrypt-communication.md
Update the environment prefix seen in the documentation from NMS to NGINX_AGENT
=> Update environment variables from NMS to NGINX_AGENT

site/content/configuration/configuration-overview.md
This pull request changes the warning callout about prefix changes to be more prominent and precise, and adjusts the formatting of the config-dirs note for readability.
=> Update the flag & environment table callouts

.github/workflows/release-branch.yml
Changed npm install command in GitHub workflow to pin the semver package version to 7.6.2
=> chore: pin semver package version to 7.6.2

sdk/config_helpers.go, sdk/config_helpers_test.go, test/integration/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go, test/performance/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go, vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
Add deduplication for ssl certificate metadata. This handles the case where the same ssl certificates are being used many times throughout the nginx.conf. 
=> fix: add deduplication for the same ssl cert metadata

.github/workflows/ci.yml, .github/workflows/release-branch.yml, Makefile.packaging, sdk/config_helpers.go, sdk/config_helpers_test.go, test/integration/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go, test/performance/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go, vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
=> Fix release workflow

site/content/configuration/encrypt-communication.md
=> Fix incorrect bold tag in heading

internal/bus/topics.go, internal/command/command_plugin.go, internal/command/command_plugin_test.go, internal/command/command_service.go, internal/command/command_service_test.go, internal/command/commandfakes/fake_command_service.go, internal/file/file_manager_service.go, internal/file/file_manager_service_test.go, internal/file/file_plugin.go, internal/file/file_plugin_test.go, internal/watcher/instance/nginx_config_parser.go, internal/watcher/instance/nginx_config_parser_test.go, nginx-agent.conf, test/integration/grpc_management_plane_api_test.go, test/mock/grpc/mock_management_command_service.go, test/protos/data_plane_response.go
=> Upload nginx config

README.md
the current url shows 404
I'm not completely sure if this one is 100% correct, but it's better than 404: https://docs.nginx.com/nginx-agent/installation-upgrade/container-environments/docker-images/
=> URL fix for building docker image in README.md

internal/watcher/instance/instance_watcher_service.go, internal/watcher/instance/instance_watcher_service_test.go
Fix check for comparing children PIDs
=> Fix check for comparing children PIDs

site/content/changelog.md
Update the changelog in docs.nginx.com with the latest releases
=> docs: update changelog

pkg/files/file_helpers.go, pkg/files/file_helpers_test.go
Added DetermineFileAction to pkg/files/file_helpers.go which compares two lists of files, determines the action needed for each file and then returns a list of files with the file action set for each file
=> Add DetermineFileAction Function 

internal/file/file_plugin.go, internal/file/file_plugin_test.go, internal/resource/resource_plugin.go, internal/resource/resource_plugin_test.go, test/mock/grpc/mock_management_file_service.go
- Cleaned up data plane response messages so they are consistent and no longer contain the instanceID
- Errors are cleaned up so Config apply original error is sent with failure status instead of the rollback error, rollbacks status is also included in the message for a config apply failure if rollback has occurred 
- Added additional checks to the unit tests to check the errors being sent in the data plane responses instead of just checking the topic
=> Fix data plane response messages and errors

site/content/changelog.md
This commit updates the Agent changelog for the 2.36 and 2.36.1 releases.
=> feat: Update the changelog

.github/workflows/release-branch.yml, Makefile, Makefile.packaging, scripts/packages/packager/local-entrypoint.sh, scripts/packages/packager/signed-entrypoint.sh
We encountered a bug where the output of
```bash
nginx-agent -v
nginx-agent version 2.36.0-cb1fc63a
```
produced a version without the letter 'v' prepended, which does not conform to correct formatting.
This PR ensures that we always prepend the letter 'v' to the output of the '-v' CLI flag.
=> The letter v is now always prepended to output of -v

Makefile, docs/architecture/README.md, docs/architecture/config_apply.md, docs/architecture/config_apply_rollback.md, docs/architecture/config_apply_state.md
Added flowchart and states for config apply
Stopped the Docs folder being deleted when running make clean 
=> Config Apply Diagrams

site/content/configuration/configuration-overview.md, src/core/config/config.go, src/core/config/config_test.go, src/core/config/defaults.go, src/core/config/types.go, src/core/grpc.go, src/plugins/testdata/configs/updated.conf, test/integration/vendor/github.com/nginx/agent/v2/src/core/config/config.go, test/integration/vendor/github.com/nginx/agent/v2/src/core/config/defaults.go, test/integration/vendor/github.com/nginx/agent/v2/src/core/config/types.go, test/integration/vendor/github.com/nginx/agent/v2/src/core/grpc.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/config/config.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/config/defaults.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/config/types.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/grpc.go
added metrics backoff settings so they are different from the command backoff. This allows us to set the `max_elapsed_time` to something not 0 that would drop metrics from the buffer after that timeout period
=> Fix backoff to drop Metrics Reports from buffer after max_elapsed_time has been reached

.github/workflows/ci.yml, Makefile.containers, scripts/packages/nginx-agent.service, scripts/packages/postinstall.sh, scripts/packages/postremove.sh, scripts/packages/postupgrade.sh, scripts/packages/preremove.sh
This PR aims to prevent silent fails when agent is installed in a Debian docker image. PostInstall.sh no longer uses the ps command to detect nginx users.
=> Fix Post Install Script Issues

Makefile, src/core/metrics/sources/nginx_plus.go, src/core/metrics/sources/nginx_plus_test.go, src/core/nginx.go, src/plugins/metrics.go, src/plugins/metrics_throlling.go, test/integration/vendor/github.com/nginx/agent/v2/src/core/nginx.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/nginx_plus.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/nginx.go, test/performance/vendor/github.com/nginx/agent/v2/src/plugins/metrics.go, test/performance/vendor/github.com/nginx/agent/v2/src/plugins/metrics_throlling.go
Increased the timeout period for collecting metrics. Have added additional context for debugging so issue is easier to identify in the future
=> Increase timeout period for collecting metrics

site/content/installation-upgrade/installation-oss.md, site/content/installation-upgrade/installation-plus.md, site/content/installation-upgrade/uninstall.md
=> Add instructions for Amazon Linux 2023

.github/workflows/docs-build-push.yml
Adds top-level read permission to docs-build-push.
=> Define top level read permission for docs-build-push

site/content/changelog.md, site/go.mod, site/go.sum
Links to releases in the changelog are missing a `:` after https.
(This is an issue in the template for the changelog script that has been fixed separately)
=> docs: fix github links in changelog

scripts/packages/postinstall.sh
Fix post install script for when no nginx instance is installed.
=> Fix post install script for when no nginx instance is installed

site/content/installation-upgrade/installation-oss.md, site/content/installation-upgrade/installation-plus.md
Update the NGINX GPG keys in the agent docs
Before: 
```
When prompted to accept the GPG key, verify that the fingerprint matches 573B FD6B 3D8F BC64 1079 A6AB ABF5 BD82 7BD9 BF62, and if so, accept it.
```
After:
```
When prompted to accept the GPG key, verify that the fingerprint matches 8540 A6F1 8833 A80E 9C16 53A4 2FD2 1310 B49F 6B46, 573B FD6B 3D8F BC64 1079 A6AB ABF5 BD82 7BD9 BF62, 9E9B E90E ACBC DE69 FE9B 204C BCDC D8A3 8D88 A2B3, and if so, accept it.
```
=> docs: update GPG keys

internal/logger/logger.go, internal/model/config.go, internal/model/config_test.go, internal/resource/resource_plugin.go, internal/watcher/instance/instance_watcher_service.go, internal/watcher/instance/nginx_config_parser.go, internal/watcher/watcher_plugin.go, internal/watcher/watcher_plugin_test.go
- Added checks to ensure that we only send NGINX config context updates if there is a change to the NGINX config
- Added checks to prevent NGINX config context updates from being sent while a config apply is in progress
- Added extra debug logging
=> Only send NGINX config context updates if there is a change

site/content/_index.md, site/content/changelog.md, site/content/configuration/_index.md, site/content/contribute/_index.md, site/content/export-metrics.md, site/content/installation-upgrade/_index.md, site/content/installation-upgrade/container-environments/_index.md, site/content/installation-upgrade/uninstall.md, site/content/v2/_index.md, site/content/v2/configuration/_index.md, site/content/v2/installation-upgrade/_index.md, site/content/v2/installation-upgrade/container-environments/_index.md
This commit adds a placeholder document for exporting metrics, and adds the key template information for how-to documents to the exporting metrics and migrating from v2 to v3 pages.
It also cleans up metadata description instances on the folder index pages.
=> feat: Add placeholder document for exporting metrics, update pages

sdk/grpc/grpc.go, test/integration/vendor/github.com/nginx/agent/sdk/v2/grpc/grpc.go, test/performance/vendor/github.com/nginx/agent/sdk/v2/grpc/grpc.go, vendor/github.com/nginx/agent/sdk/v2/grpc/grpc.go
Update the Agent to take MaxSendMsgSize and MaxRecvMsgSize values in defaults for client and server options
=> Add MaxRecvMsgSize and MaxSendMsgSize to client and server options

src/core/config/config.go, test/integration/vendor/github.com/nginx/agent/v2/src/core/config/config.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/config/config.go
Fix name for deprecated flag to remove warning from logs
Before:
```
nginx-agent -v
WARN[0000] Error occurred deprecating flag metrics-bulksize: flag "metrics-bulksize" does not exist 
```
After 
```
nginx-agent -v
nginx-agent version v2.37.0
```
=> fix name of deprecated flag

src/core/payloads/register_software_details_test.go, src/extensions/advanced-metrics/aggregator/leak_test.go, src/extensions/advanced-metrics/ingester/leak_test.go, src/extensions/advanced-metrics/pkg/advanced-metrics/advanced_metrics_test.go, src/extensions/advanced-metrics/pkg/advanced-metrics/leak_test.go, src/extensions/advanced-metrics/pkg/publisher/leak_test.go, src/extensions/advanced-metrics/pkg/schema/leak_test.go, src/extensions/advanced-metrics/pkg/schema/schema_builder_test.go, src/extensions/advanced-metrics/reader/leak_test.go, src/extensions/advanced-metrics/tables/leak_test.go, src/extensions/advanced-metrics/tables/limits/leak_test.go, src/extensions/advanced-metrics/tables/lookup/leak_test.go, src/extensions/advanced-metrics/tables/priority_table/leak_test.go, src/extensions/advanced-metrics/tables/sample/leak_test.go, src/extensions/advanced-metrics/tables/schema/field_test.go, src/extensions/advanced-metrics/tables/schema/leak_test.go, src/extensions/advanced-metrics/tables/schema/schema_test.go, src/extensions/leak_test.go, src/extensions/nginx-app-protect/monitoring/manager/leak_test.go, src/extensions/nginx-app-protect/monitoring/processor/leak_test.go, src/extensions/nginx-app-protect/nap/leak_test.go, src/extensions/prometheus-metrics/leak_test.go
Added leak tests for Agent and increased test coverage
=> added leak tests for agent v2

Makefile, scripts/docker/nginx-oss/apk/Dockerfile, scripts/docker/nginx-oss/deb/Dockerfile, scripts/docker/nginx-oss/rpm/Dockerfile, scripts/docker/nginx-plus/almalinux/Dockerfile, scripts/docker/nginx-plus/alpine/Dockerfile, scripts/docker/nginx-plus/amazonlinux/Dockerfile, scripts/docker/nginx-plus/centos/Dockerfile, scripts/docker/nginx-plus/debian/Dockerfile, scripts/docker/nginx-plus/oraclelinux/Dockerfile, scripts/docker/nginx-plus/redhatenterprise/Dockerfile, scripts/docker/nginx-plus/rockylinux/Dockerfile, scripts/docker/nginx-plus/suse/Dockerfile, scripts/docker/nginx-plus/ubuntu/Dockerfile, scripts/packages/postinstall.sh
* Update `make image` & `make oss-image` to take a `NGINX_AGENT_VERSION` argument
* Update `make oss-image` to take a `IMAGE_BUILD_TARGET` argument
* Fix postinstall script error when running on SUSE OS (`awk` wasn't installed so I used `cut` instead)
Can now call make targets like this now:
```
IMAGE_BUILD_TARGET=install-agent-repo NGINX_AGENT_VERSION=2.37.0 OS_RELEASE=alpine OS_VERSION=3.20 make oss-image
```
```
NGINX_AGENT_VERSION=2.37.0 OS_RELEASE=alpine OS_VERSION=3.20 make image
```
=> Fix make image targets

test/integration/api/nginx-agent.conf, test/integration/features/test_configs/nginx-agent-config.conf, test/integration/features/test_configs/nginx-agent-counting.conf, test/integration/features/test_configs/nginx-agent-metrics.conf, test/integration/grpc/grpc_config_apply_test.go
If the integration tests fail we archive the container logs to help solve the failure, currenlty the agent log level is set to info for these tests which makes them hard to debug.
=> Set log level to debug for inetegration tests

Makefile.packaging
Currently  if the GPG private key used for package signing is invalid or expired the pipelines still pass. This adds a check that will fail the pipeline if there's a problem with the key.
Example
```
$ make package
$(gpg --import $AGENT_GPG_KEY); \
keyid=$(gpg --list-keys NGINX | egrep -A1 "^pub" | egrep -v "^pub" | tr -d '[:space:]'); \
if [ -z "$keyid" ]; then echo "Error: GPG key not found."; exit 1; fi; \
if gpg --list-keys --with-colons "$keyid" | grep -E '^pub:e:|^uid:e:'; then \
echo "Error: GPG key has expired."; \
exit 1; \
fi; \
$(gpg --output .key --armor --export $keyid)
gpg: key <redacted>: public key "NGINX NIM (Signing key) <support@nginx.com>" imported
gpg: key <redacted>: secret key imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg:       secret …
```
=> Add checks for expired package signing key

internal/watcher/instance/nginx_process_parser.go
Change process parser log level from warning to debug.
=> Change process parser log level

Makefile.packaging
Currently if the GPG private key used for package signing is invalid or expired the pipelines still pass. This adds a check that will fail the pipeline if there's a problem with the key.
```
$ make package
$(gpg --import $AGENT_GPG_KEY); \
keyid=$(gpg --list-keys NGINX | egrep -A1 "^pub" | egrep -v "^pub" | tr -d '[:space:]'); \
if [ -z "$keyid" ]; then echo "Error: GPG key not found."; exit 1; fi; \
if gpg --list-keys --with-colons "$keyid" | grep -E '^pub:e:|^uid:e:'; then \
echo "Error: GPG key has expired."; \
exit 1; \
fi; \
$(gpg --output .key --armor --export $keyid)
gpg: key <redacted>: public key "NGINX NIM (Signing key) <support@nginx.com>" imported
gpg: key <redacted>: secret key imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg:       secret keys read: …
```
=> Add check for expired GPG key

internal/collector/otel_collector_plugin_test.go, internal/collector/otelcol.tmpl, internal/collector/settings_test.go, internal/config/types.go, test/config/collector/test-opentelemetry-collector-agent.yaml, test/mock/collector/grafana/provisioning/dashboards/host-metrics.json, test/mock/collector/nginx-agent.conf, test/types/config.go
Introduced the option for the users to set the scraper for the Host metrics receiver from the nginx agent conf. 
=> Update host metrics receiver

internal/file/file_plugin.go, internal/file/file_plugin_test.go
This change alters the handling of the `model.RollbackRequired` status in the file plugin to avoid running the validation step in cases where a config apply fails due to a file operation error.
=> Avoid running config validation when file action fails

.github/workflows/ci.yml, .github/workflows/release-branch.yml
See here for more details on the issue https://github.com/actions/setup-go/issues/403
=> Set cache equal to false for setup-go github action

Makefile, test/docker/performance/Dockerfile
The performance tests make target is incorrect, fixing and renaming other targets for consistency
=> Fixed make target pointing at wrong Dockerfile and renamed others to be consistent

internal/collector/otelcol.tmpl, internal/config/config_test.go, internal/config/types.go, test/mock/collector/nginx-agent.conf, test/types/config.go
If the health extension configuration is missing in the `nginx-agent.conf` then the collector will fail to start.
This PR fixes that issue by allowing the collector to start with no extensions configured.
=> Fix collector extensions config

.github/workflows/ci.yml, .github/workflows/release-branch.yml, internal/collector/nginxossreceiver/internal/metadata/generated_status.go, internal/collector/nginxplusreceiver/internal/metadata/generated_status.go
With this change a package will be published every time a commit is merged in the `v3` branch. 
The value of the build number is dynamic which increments each time the workflow is run.
GITHUB_RUN_NUMBER : It's part of the default environment variables that GitHub sets are available to every step in a workflow. A unique number for each run of a particular workflow in a repository. This number begins at 1 for the workflow's first run, and increments with each new run. This number does not change if you re-run the workflow run. For example, 3.
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables
=> Publish package for agent

site/go.mod, site/go.sum, site/hugo-entrypoint.sh, site/makefile
Cherry pick [7087de1f30b3910b2991f8c8b6b51588752aeb46](https://github.com/nginx/agent/commit/7087de1f30b3910b2991f8c8b6b51588752aeb46)
=> Add hugo version check and theme update to Makefile

.github/workflows/docs-build-push.yml, site/config/_default/config.toml
This enables `enableGitInfo` config and bumps docs-action version to fix incorrect `last-modified` docs values
=> docs: enableGitInfo config and docs-action bump

test/integration/grpc_management_plane_api_test.go
The integration tests in the pipelines are failing as there is an error removing the network, adding a log to find the exact error. 
=> Log error from integration test

site/config/docker/config.toml, site/go.mod, site/go.sum, site/hugo-entrypoint.sh
Fix docs docker failing without git context. Since adding `LastMod`, a proper git history is required during hugo build time. The mount point in docker doesn't pull in the `.git` directory, so it would always fail.
=> Fix docs docker failing without git context

pkg/tls/self_signed_cert.go
Improve some comments, make the struct and some functions public for better visibility in pkgsite
=> Improve comments for docs, make private objects public

README.md, site/content/configuration/encrypt-communication.md, site/content/overview.md
Recent NIM docs reog means `https://docs.nginx.com/nginx-management-suite/nim` is no longer valid. PR to update links to  to `https://docs.nginx.com/nginx-instance-manager`.
Note: pages are still rendering as the pages are still in Azure for the moment.
=> Docs: updating links from /nginx-management-suite/nim to /nginx-instance-manager

site/content/installation-upgrade/container-environments/docker-images.md, site/content/installation-upgrade/getting-started.md, site/go.mod, site/go.sum
- Fixes a link to the wrong guide
- Removes section referencing dockerfiles that are not available any more
=> docs: Fix NGINX install link and dockerfile section

internal/collector/otel_collector_plugin_test.go, internal/command/command_plugin.go, internal/command/command_plugin_test.go, internal/command/command_service.go, internal/command/command_service_test.go, internal/datasource/proto/message.go, internal/datasource/proto/message_test.go, internal/file/file_manager_service.go, internal/file/file_plugin.go, internal/file/file_plugin_test.go, internal/logger/logger.go, internal/resource/resource_plugin.go, internal/watcher/file/file_watcher_service_test.go, internal/watcher/instance/nginx_config_parser_test.go, internal/watcher/watcher_plugin_test.go, pkg/uuid/uuid.go, pkg/uuid/uuid_test.go, test/helpers/os_utils.go, test/helpers/os_utils_test.go, test/helpers/slog_utils.go, test/integration/install_uninstall_test.go, test/mock/grpc/mock_management_command_service.go, test/mock/grpc/mock_management_file_service.go, test/protos/data_plane_response.go
Update the message id from uuid v4 to v7
=> Set the message identifiers as UUIDv7

.github/workflows/ci.yml, internal/command/command_service.go, internal/command/command_service_test.go, internal/resource/resource_service.go, test/integration/grpc_management_plane_api_test.go
If the agent looses connection to the management plane try to reestablish the connection and send a create connection request. 
=> Send create connection after disconnect from management plane

api/grpc/mpi/v1/helpers_test.go
`TestConvertToStructs` was occasionally failing because it was expecting `range` over a `map` to be a consistent order, but per [spec]:
> The iteration order over maps is not specified and is not guaranteed to be the same from one iteration to the next.
Uses `ElementsMatch` so the test passes even when the order of elements is different.
[spec]: https://go.dev/ref/spec#RangeClause
=> fix: flaky test

site/go.mod, site/go.sum
Bump the Hugo theme to the latest version
=> docs: theme bump

internal/watcher/instance/nginx_config_parser.go, internal/watcher/instance/nginx_config_parser_test.go
Check if cert is already in NginxConfigConext Files before adding cert. Certs which are referenced multiple times in a config no longer appear multiple times in the FileOverview etc 
=> Remove duplicate entires of certs in files

scripts/packages/postinstall.sh, scripts/packages/postremove.sh, scripts/packages/preinstall.sh
Removed the creation of the agent-dynamic.conf file and setting instance-groups
Remove FreeBSD specific commands 
=> Remove unsupported from agent v3 install

scripts/packages/postinstall.sh
Update post install script to modify ownership of /etc/nginx-agent, /var/log/nginx-agent, /var/lib/nginx-agent 
=> Update Post Install Script

.github/workflows/release-branch.yml
Updates the package publish location for CI
=> chore: update package publish location

.github/workflows/release-branch.yml
Use a self-hosted runner to run the Publish job as public runners lack access to the host.
=> Change self hosted runner tag

internal/config/config.go
=> Add error & label to log

internal/command/command_plugin.go, internal/command/command_service.go, internal/command/command_service_test.go, internal/command/commandfakes/fake_command_service.go, internal/file/file_plugin.go, internal/grpc/grpc.go, internal/resource/resource_plugin.go, internal/watcher/watcher_plugin.go
When a token is updated a create connection request is now sent
- We now check if the error during the create connection callback is that the grpc connection is closing. If this is the error we then stop trying to create a connection as it will not be successful until a new connection is created which it wont be able to do until exiting the callback. 
- also added logs about closing the plugins to make it more clear what is happening
=> Send create connection after updating credentials

Makefile
Update build-test-oss-image and build-test-plus-image make targets to take into account the OS type.
=> Update build-test-oss-image and build-test-plus-image make targets to take into account the OS type

Makefile, test/mock/collector/README.md, test/mock/collector/nginx-plus-and-nap/docker-compose.yaml
- Added two new make targets to run and stop the mock otel collector without running NAP
- Creating a `docker-compose` file specifically for running with NAP
- Edited the old `docker-compose` file to not use NAP
- Updated `README.md` with steps on how to build without NAP
=> Create make collector target without NAP

internal/watcher/file/file_watcher_service.go, internal/watcher/instance/nginx_process_parser.go, internal/watcher/instance/nginx_process_parser_test.go
Changed process parser to check that the process is a master process before adding it to the list of instances. 
Added test to check that the process parser doesn't pick up the cache manager process as a master process
Removed Log for skipping an event 
=> Ignore NGINX cache manager process when looking for NGINX master process

scripts/packages/preinstall.sh
Addressing issue during upgrade from v2 to v3
dpkg: error processing archive /home/ubuntu/deb/nginx-agent_3.0.0-4878~jammy_amd64.deb (--unpack):
new nginx-agent package pre-installation script subprocess returned error exit status 1
=> Fix upgrade v2 to v3

internal/collector/nginxplusreceiver/factory.go, internal/config/types.go, test/mock/collector/nginx-agent.conf
Fix to start the NGINX plus scraper.
=> Fix to start the NGINX plus scraper

internal/collector/nginxplusreceiver/factory.go, internal/watcher/instance/nginx_process_parser.go, internal/watcher/instance/nginx_process_parser_test.go
- Set config path attribute when `nginx -c <filepath>` is used
- Created new unit test for getting the config path from the command
=> Add setting config path from NGINX process

.github/workflows/ci.yml, .github/workflows/release-branch.yml
- Remove the `workflow_call` trigger from `release-branch.yml` workflow. 
- Remove the call to release branch workflow from the `ci.yml` workflow
=> CI: remove release workflow call on all v3 pipelines

internal/collector/otelcol.tmpl
For testing purposes, it makes life easier to configure whether or not to skip TLS verification in cases of self-signed certificates.
=> NGINXaaS: add skip tls verification option to otlp exporter

internal/config/config.go, internal/file/file_manager_service.go, internal/file/file_manager_service_test.go, internal/file/file_plugin.go, internal/file/file_plugin_test.go, internal/file/filefakes/fake_file_manager_service_interface.go, internal/model/config.go, internal/watcher/watcher_plugin.go, test/helpers/os_utils.go
Update manifest file during a NginxConfigContext update, mark unreferenced files in the manfiest file during config apply and configContext update. 
=> Update Manifest file during a ConfigContextUpdate

internal/config/defaults.go, test/docker/load/Dockerfile
Update default backoff settings to 
- now try for 1 minute instead of 30 seconds
- try 3 times in 30 seconds and 5 times in 1 minute instead of 9+ times in 30s
=> Update Default Backoff Settings

api/grpc/mpi/v1/command.pb.go, api/grpc/mpi/v1/command.proto
Remove validation that doesn't allow underscores in a hostname. 
- Docker allows you to set a hostname to have an underscore `docker run --hostname example_test.net test_image`
=> Allow underscores in hostname

Makefile
- Modifies LDFLAGS to remove the symbol table from the binary
- print build command during `build` make target
=> Remove symbol table from build

README.md
Since we have discontinued the Slack NGINX community, I have updated the README to point to the NGINX Community Forum and specifically to the "Agent" tag section
Updated to remove Slack reference and replace with Forum
- [ x] I have read the [`CONTRIBUTING`](https://github.com/nginx/agent/blob/main/docs/CONTRIBUTING.md) document
- [ x] I have run ```make install-tools``` and have attached any dependency changes to this pull request
- [ x] If applicable, I have added tests that prove my fix is effective or that my feature works
- [ x] If applicable, I have checked that any relevant tests pass after adding my changes
- [ x] If applicable, I have updated any relevant documentation …
=> Changed README to reflect new community forum

.golangci.yml, Makefile.tools, README.md, internal/datasource/host/info_test.go
Without these changes I can't develop on v3 reliably; the `make lint unit-test` and the pre-push scripts fail. See the individual commits for more details of what/why they do.
- This is all non-agent changes (tests, docs)
- I ran `make test` on Ubuntu 24.04 and doubt anyone has run make test on any of the above listed platforms recently because any distro that has an `/etc/os-release` that doesn't _exactly_ match the test expectation will fail.
=> Update linter version and install instructions in README.md

internal/collector/otel_collector_plugin.go, internal/file/file_manager_service.go, internal/watcher/instance/instance_watcher_service.go, internal/watcher/process/process_operator.go
Fix Race conditions caused by 
- OTel collector modifying back off settings 
- Instance Cache being updated 
- Process being converted 
=> Fix race conditions

internal/grpc/grpc.go, internal/grpc/grpc_test.go, test/helpers/cert_utils.go
This is a duplicate of https://github.com/nginx/agent/pull/1079
=> Allow only CA cert to be set in command server TLS settings

internal/file/file_manager_service.go, internal/file/file_manager_service_test.go, internal/file/filefakes/fake_file_manager_service_interface.go
Handle scenario where agent tries to delete a file that does not exist during a config apply.
=> Handle scenario where agent tries to delete a file that does not exist during a config apply

internal/logger/logger.go
Fix debug log format.
Example log line:
```
2025-06-13 11:13:33 time=2025-06-13T10:13:33.917Z level=DEBUG source=resource/resource_plugin.go:54 msg="Starting resource plugin"
```
=> Fix debug log format

sdk/config_helpers.go, src/core/config/config.go, src/core/config/defaults.go, src/core/config/types.go, src/core/metrics/collectors/nginx.go, src/core/metrics/sources/nginx_plus.go, src/core/metrics/sources/nginx_plus_test.go, test/integration/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go, test/integration/vendor/github.com/nginx/agent/v2/src/core/config/config.go, test/integration/vendor/github.com/nginx/agent/v2/src/core/config/defaults.go, test/integration/vendor/github.com/nginx/agent/v2/src/core/config/types.go, test/performance/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/config/config.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/config/defaults.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/config/types.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/collectors/nginx.go, test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/nginx_plus.go
Check for ssl in listen directive to determine is an endpoint is using http or https
=> Add check to see if SSL is enabled for Plus API

internal/config/defaults.go, test/config/agent/nginx-agent-otel-load.conf, test/config/collector/test-opentelemetry-collector-agent.yaml
Update batch processor defaults.
=> Update batch processor defaults

test/helpers/cert_utils.go
Potential fix for [https://github.com/nginx/agent/security/code-scanning/164](https://github.com/nginx/agent/security/code-scanning/164)
To fix the issue, the `bits` constant should be updated to use a secure key size of at least 2048 bits. This change ensures compliance with modern cryptographic standards and mitigates the risk of brute-force attacks. The fix involves modifying the `bits` constant definition and ensuring that the updated value is used in the `rsa.GenerateKey` function.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Update cert utils

.github/workflows/upload-release-assets.yml
=> [CI/CD] Fix debian package naming

internal/collector/otel_collector_plugin.go, internal/collector/otel_collector_plugin_test.go, internal/datasource/config/nginx_config_parser.go, internal/datasource/config/nginx_config_parser_test.go, internal/model/config.go, internal/resource/resource_service_test.go, test/config/nginx/nginx-with-multiple-syslog-servers.conf, test/config/nginx_config.go, test/model/config.go
- If syslog server is not "localhost" or "127.0.0.0" ignore it 
- If a syslog server is not valid if multiple are configured try the next
- Check if port is already in use 
- Only allow one syslog server for NAP
=> Parse NGINX Config for Valid NAP Syslog Server

internal/collector/otel_collector_plugin.go, internal/collector/otel_collector_plugin_test.go, internal/datasource/config/nginx_config_parser.go, internal/datasource/config/nginx_config_parser_test.go, internal/model/config.go, internal/resource/resource_service_test.go, test/model/config.go
Fix how NAP syslog servers are discovered
=> Fix how NAP syslog servers are discovered

Makefile.packaging
Adds back the `gpg-key` job to run as part of the `package` make target.
=> [CI/CD] add missing key generation

internal/config/config.go, internal/config/config_test.go
If the log level of the the OTel collector is not set in `nginx-agent.conf` set the log level to match that of the Agent log level unless the log level is unsupported by OTel. 
Add validation when setting agent log is "error", "warn", "info" or "debug"
=> Set OTel Collector Log Level To Match Agent

.github/workflows/ci.yml, Makefile
Includes some CI/CD fixes:
- Adds a new job `sanity-check` which will run a build using the Development Go module repository as a `GOPROXY`. This willl not run on forked repos, and is used to check that all our dependencies are in place for builds which use this proxy.
- Fetch tags during code checkouts to allow for correct versioning when building locally
- Sets the Version check in `Makefile` to mimic the `v2` logic, first check the `git describe` output, and if not present then pull the latest tag and set it to that (`v3.2.0` at time of writing)
- Re-enables the performance test benchmark results being posted to the `benchmark-results` branch for observation. This was being run in the pipeline but hasn't been updated since the branch switchover.
Before creating a PR, run through this …
=> [CI/CD] Various fixes

.github/workflows/ci.yml
Allows the Actions to write badges and test results into the repo during runs on main.
=> [CI/CD] add write permissions for updating badge and pushing test results

Makefile
=> Fix performance test output

.github/workflows/ci.yml, .github/workflows/mend.yml
Disables jobs that require secrets during a dependabot update PR
=> disable jobs which require secrets when PR is a dependabot update

internal/datasource/config/nginx_config_parser.go, internal/datasource/config/nginx_config_parser_test.go
Fix NGINX stub_status and plus api discovery.
=> Fix NGINX stub_status and plus api discovery

internal/file/file_manager_service.go, internal/file/file_service_operator.go, internal/file/file_service_operator_test.go
If agent is not connected yet set the max elapsed time to 0 so that agent retries indefinitely on startup to send the initial file overview update.
=> Ensure that a file overview update is performed even if the initial create connection request takes a long time

internal/collector/logsgzipprocessor/processor_benchmark_test.go
Updates the release branch with a test fix from main which was added as part of updating the OTel dependencies. It should fix the benchmark test failing in release branch CI pipeline.
=> Fix Performance Benchmark for release-3.3.2

internal/file/file_manager_service.go, internal/file/file_manager_service_test.go
Add back in the file permission validation that was missed while resolving conflicts with main
=> Fix file permission validation
